### ISSUE TITLE
Split public API from internal implementations 

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#1]
A generic point that we should start thinking about is to make it clear (by package name) what is internal and public API meant to be directly used and extended by clients. This will give us more flexibility in the future when doing modifications as we'll know what we can change without affecting existing language-specific client implementations.

[migrated from https://github.com/eclipsesource/graphical-lsp/issues/363]

**Comment by planger** [comment]
Also restructure the code in the server so that packages are structured by capability rather than by action, handler, provider, etc.
One package concerns one capability and includes all relevant classes for the capablity.
