### ISSUE TITLE
Discussion: Restructure & document project templates

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#1012]
After the 2.0 Release before adapting the `glsp-examples` repository we should discuss/think about the current project templates structure.

- Currently we always have a speration in a dedicated `glsp-client` and `glsp-server` repository. While this structuring makes sense in combination with a Java GLSP server (two different languages, java server has to run in separate process) its not ideal for node servers. Here it makes more sense to keep both server and client in one mono repo.
- In addition, the upcoming 2.0 version will  provide generic support for multiple different server connection modes like: external process via socket, external process via websocket, directly in the same process (vscode extension,theia backend), direct websocket without a backend routing, pure web based via web worker, pure web based in web extension etc. We have to think about how we want to incorporate this into the project templates.
- For node-based servers connection via external process is probably not ideal. Here it makes more sense to run the server directly in the backend context without the overhead of an extra process and additional communication json-rpc communication layer.
- A common use case for the vscode template is packing & publishing of the extension. Currently this is not well supported by the template out of the box and a lot of changes are required for successful packaging. (see also https://github.com/eclipse-glsp/glsp/discussions/1010)

From the top of my head I would propose the following changes:
- Restructure node based project templates to the following structure
   ```
    +template
       + tasklist-client
       + tasklist-server
       + application specific packages (e.g. tasklist-browser-app, tasklist-theia) 
      - lerna.config
      - package.json
   ```

 - Adapt vscode templates for publishing by
    - proper bundling extension, webview & server code with webpack
    - add `vsce` as dev dependency and provide `package` script
  - Decide for one default connection-mode  (e.g. external process + socket) but also
     - Add in-detail documentation about the different connection modes + snippets to the website doc and
     - Mention the different modes + doc in the README of the templates

In the longrun switching to a guided generator process with `yeoman` could also make sense.

@planger  @martin-fleck-at  WDYT?

**Comment by martin-fleck-at** [comment]
Thank you very much for raising this topic, Tobias! I agree that we should carefully think about this restructuring and also what should be present in which example. I like your proposed changed, especially the decision on a default connection mode with detailed documentation for other methods - just to avoid confusion for adopters on what connection mode needs to be available. I also agree that a guided process through `yeoman` should be our long-term way to go as by now there are quite a lot of paths people can take when using GLSP. Maybe we should even think about using yeoman in the short-term.

Happy to pick that up when we are closer to the release.

**Comment by planger** [comment]
I also agree, for node-based projects, a mono-repo would be much better! :+1: Thanks for bringing that up.
