### ISSUE TITLE
How to handle clear/timeout ServerMessages

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#1019]
Currently the server side `ServerMessageAction` API provides features to send clear messages (which should clear all currently visible notifications) and messages with a timeout (notification will be disposed after the timeout).
However, depending on the application frame the notification system may not support those features (e.g. VS Code).
We should provide a possibility to let the server know whether the full notification feature set is supported (e..g by passing the information as part of the initialize request).
This allows adopters to adapt the send `ServerActionMessages` to the feature set of the client.
If not configured only the basic minimal feature set (no clear, no timeout) should be supported.

---

It has been decided to introduce progress support and drop the timeout for `ServerMessageAction`.
- [x] Client + Protocol: https://github.com/eclipse-glsp/glsp-client/pull/265
- [x] Website: https://github.com/eclipse-glsp/glsp-website-source/pull/91
- [x] Node server: https://github.com/eclipse-glsp/glsp-server-node/pull/52
- [x] Java server: https://github.com/eclipse-glsp/glsp-server/pull/205
- [x] Theia integration: https://github.com/eclipse-glsp/glsp-theia-integration/pull/168
- [x] VS Code integration: https://github.com/eclipse-glsp/glsp-vscode-integration/pull/47
- [x] Eclipse integration: postponed with https://github.com/eclipse-glsp/glsp/issues/1055

**Comment by planger** [comment]
Isn't there some API in VS Code (and in Theia actually) to show a progress instead of a notification? Imho that would be the nicest solution. WDYT?

**Comment by tortmayr** [comment]
Server side progress report support would be a great feature and would indeed solve the issue.
So what we could do a rework for the notification API so that
- `ServerMessageActions` are one time notifications that have no timeout and are simply forwarded to the notification system of the client application frame
- We drop the concept of "clear messages" and message timeouts and instead introduce a new `ServerProgressAction` that can than be handled with the respective progress API on the client side
