### ISSUE TITLE
Refactor tools and toolfeedback

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#102]
Currently tools, and their corresponding feedback, are split into separate modules on client side. However, since Feedback is never dispatched without the corresponding tool it doesn't make sense to split them at all. It probably would be better to provide separate modules for each tool that bind the necessary stuff (tool itself, feedback commands etc.)
The `toolFeedbackModule` should be droppend entirely and the the `FeedbackActionDispatcher`should be bound in the base module. We could even think of merging the `FeedbackActionDispatcher` with the `GLSPActionDispatcher`.

**Comment by planger** [comment]
As discussed, I think we should move generic feedback mechanism into base. Consider merging GLSP action dispatcher with feedback dispatcher. Move marker feedback into marker module.
