### ISSUE TITLE
Theia disconnects all clients after closing single client

### ISSUE THREAD

**Issue by haydar-metin** [eclipse-glsp/glsp#1030]
If you open in Theia multiple examples and then close one tab/browser, then Theia disconnects also all other clients.

## Demo

Tested with https://github.com/eclipse-glsp/glsp-theia-integration/commit/d3fcc5a5a42051e8913298edbcdbbb718262249a 

1. Start the application with `yarn start`
2. Open two browsers/tabs and open two examples with Theia (can be the same file or different)
3. Close one browser/tab
4. The other browser/tab will show an error

https://github.com/eclipse-glsp/glsp/assets/13104167/d80c6909-cbc4-4e2e-875a-e614d69e9719

**Comment by planger** [comment]
In our dev call, we decided to take out the explicit shutdown.
