### ISSUE TITLE
Guava Version Binding

### ISSUE THREAD

**Issue by N1k145** [eclipse-glsp/glsp#1046]
Currently the glsp-server is using Guava 30 with  Guice 5.0.1 which is fine. But these are only set as min versions without a max version set.

This becomes an issue when we try to integrate into a current eclipse version where other components already use higher versions of Guava.

My proposal would be to define the correct version bounds for the dependencies. For example [30.1,31). Like other components already do (xtext, mylin)

**Comment by N1k145** [comment]
@planger thanks for the review and closing the Issue, but there is a second PR for the eclipse integration with the same issue.

**Comment by planger** [comment]
> @planger thanks for the review and closing the Issue, but there is a second PR for the eclipse integration with the same issue.

Yes, sure! I'm on it (just had a meeting in between). This issue just got closed, because your PR mentions that it "closes" the issue, so it got auto-closed on merge.

**Comment by N1k145** [comment]
Sorry, I was not aware of the auto closing, it looked like you closed it.
