### ISSUE TITLE
Improve Eclipse GLSPEditorRegistry

### ISSUE THREAD

**Issue by rsoika** [eclipse-glsp/glsp#1051]
During implementing a Eclipse Integration for my GLSP server I sumbled over a NullPointer Excepiton in `GLSPDiagramEditor.init()`

To provide the developer with more information I suggest the following small enhancement in `org.eclipse.glsp.ide.editor.GLSPEditorRegistry`:

```java
   /**
    * Returns a GLSP Server Manager by an editorID. 
    *  
    * @param editorId
    * @return server manager, or throws exception if the editorId is unknown
    */
   public Optional<GLSPServerManager> getGLSPServerManager(final String editorId) {
      GLSPServerManager manager = editorIdToServerManager.get(editorId);
      if (manager == null) {
         throw new GLSPServerException("Unable to resolve GLSPServerManger by id: '" + editorId + "'");
      }
      return Optional.of(editorIdToServerManager.get(editorId));
   }
```

Maybe you find a better way with dealing with the `Optional`. But with the current implementation the method does only result in a `NullPointerException`.

**Comment by planger** [comment]
Hi @rsoika,
Do you by any chance still have the stacktrace?
As far as I've seen, the only place where this method is called in the GLSP code base is in `GLSPDiagramEditor.getServerManager()`:
```java
   public GLSPServerManager getServerManager() {
      Optional<GLSPServerManager> serverManager = GLSPIdeEditorPlugin.getDefault().getGLSPEditorRegistry()
         .getGLSPServerManager(this);
      if (!serverManager.isPresent()) {
         throw new GLSPServerException(
            "Could not retrieve GLSPServerManager. GLSP editor is not properly configured: "
               + getEditorSite().getId());
      }
      return serverManager.get();
   }
```
And this method checks whether the `GLSPServerManager` is present and already throws an exception.
Or did I miss anything?
