### ISSUE TITLE
Consider renaming `di.config` files

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#1054]
For diagram feature modules of the `glps-client` we currently follow a pattern derived from sprotty and declare
the module configuration in a `di.config` file (the module is typically then default exported).

This pattern as a couple of disadvantages.
- The naming of the file does not match the name of the exported class => makes it harder to find the corresponding file (e.g.. during debugging)
- Searching for `di.config` files gives back a large list of results and you have to manually pick the file with the module code you want to inspect
- We don't consistenlty use the default export mechanism. So we and up with a inconsistent mix of normally exported and default exported modules

I would opt for a clean refactor to rename the `di.config` files (e.g change-bounds-tool-module, glsp-export-module etc) and move away from the default export approach. All modules are exported (and consumed by adopterss) via main index anyways.
So this basically just an internal refactoring that does not introduce any API breaks. This would also be more in line with how Theia names their DI modules.

While we are at it we should also have a look at the module prefixes. (glspSomeModule vs someModule).
Initially the idea was to only prefix modules that serve as a full replacement for a sprotty module with `glsp`. (e.g. `glspBoundsModule` that is used in GLSP over sprotty's `boundsModule`)
Over time this conventions got lost and now we have an inconsistent mix of prefixed and non-prefixed modules. We should reenforce this convention.

@martin-fleck-at @planger WDYT?

**Comment by martin-fleck-at** [comment]
I'm definitely all for more usability (better dev experience) and consistency! I'm definitely in favor of renaming the `di.config` files if there is no good reason to keep them as is. If someone argues against it, I'm also okay with keeping an additional suffix in addition to the actual name, e.g., `change-bounds-tool-module.config.ts` or something similar.

As for the actual module names, I agree that we currently have a mix but while we revise it, do we still believe that this is the best policy? It might be nicer that all modules have the same name (e.g., all prefixed with `glsp` or none of them) and to avoid naming conflicts with Sprotty we could re-export them with a `sprotty` prefix if we have a customization. I understand that as a developer we are much more aware of Sprotty being used as a basis for GLSP but as a user of GLSP simply consuming everything from the framework and then having different naming conventions may be a bit odd.

**Comment by planger** [comment]
I agree it is somewhat cumbersome when debugging directly in the Chrome dev tools to find the right `di.config.ts` and I can't think of a particular reason to keep this name.

> It might be nicer that all modules have the same name (e.g., all prefixed with glsp or none of them) and to avoid naming conflicts with Sprotty we could re-export them with a sprotty prefix if we have a customization.

Agreed as well, I'd opt for no prefix at all for any of them and re-exporting Sprotty types with a `Sprotty*` prefix.

**Comment by tortmayr** [comment]
Great suggestions.
One question regarding the prefixing of sprotty modules. 
Should we prefix all sprotty modules right away or only the ones that conflict (i.e. have a glsp specific replacement module)?

**Comment by martin-fleck-at** [comment]
Unless we export them under both (unprefixed and prefixed) names I'm a bit against prefixing all sprotty modules as an "end user" will still face prefixed and unprefixed modules in their own code (for a reason unclear to them).
