### ISSUE TITLE
Eclipse Integration E4

### ISSUE THREAD

**Issue by N1k145** [eclipse-glsp/glsp#1059]
I would like to use the Eclipse Integration without the E3 EditorPart below it, in a pure E4 use case.

My proposal would be to refactor the Eclipse Integration to split up the Browser Setup and Editor Integration into separate classes. So that the Browser could basically be created onto any Composite, of course with limited functionality. 
And then have two Implementations, one based on the current EditorPart and a separate pure E4 "Editor" implementation.

This would require that the GLSPEditorRegistry does not depend on the EditorPart, but rather on some Common Base of the two implementations.

**Comment by planger** [comment]
Thank you for the suggestion! This would indeed be very nice to have. At the moment, we don't have E4 support on our roadmap, but would be happy to review PRs and contributions in this direction. So please feel free to open a PR. Thank you!

**Comment by planger** [comment]
I think this issue can be closed as https://github.com/eclipse-glsp/glsp-eclipse-integration/pull/83 is merged. Please reopen if you disagree.
