### ISSUE TITLE
FeedbackCommands should rely on elementId rather than element reference

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipse-glsp/glsp#106]
Feedback Actions are meant to be dispatched multiple times, via the IFeedbackActionDispatcher. Especially, they are re-dispatched each time the model changes. Because of this, relying on element references in the FeedbackCommands causes issues, because the commands then manipulate an older version of the model, rather than being reapplied on the version that is being rendered. This causes feedback to disappear, e.g. when the server sends an update to the client.

This is especially the case for ModifyCssFeedbackCommand, which is very generic and used in many different places (Other feedback commands might be affected as well, but it seems that most of them already rely on IDs)

Note that it's fine to instantiate Actions with an SModelElement reference; but the FeedbackCommands need to rely on this element's ID

**Comment by tortmayr** [comment]
Closed eclipse-glsp/glsp-client/pull/78
