### ISSUE TITLE
[Accessibility] Active element search needs debouncing

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#1073]
The  current implementation of the active element search is not debounced.  Cycling through suggestions with the arrow  keys will overload the action dispatcher and mess up the selection feedback:
![demo](https://github.com/eclipse-glsp/glsp/assets/2311075/91fdd154-8ffd-4cf6-8a71-c61b3181c451)

**Comment by tortmayr** [comment]
@ndoschek @martin-fleck-at FYI

**Comment by tortmayr** [comment]
I can no longer reproduce this issue. @ndoschek Do you wether this was fixed with a recent change? If so, we can close this.

**Comment by ndoschek** [comment]
I can't reproduce it either. I cannot remember in detail if there was a dedicated fix, but I'd agree to close it for now.

**Comment by martin-fleck-at** [comment]
I also don't recall any particular fix for this but if it doesn't happen, let's close this issue.
