### ISSUE TITLE
Remove STACK Const from GConstants.Layout

### ISSUE THREAD

**Issue by rsoika** [eclipse-glsp/glsp#1074]
The stack layout has been removed with issue #444. This layout type was provided by sprotty and has never been actively supported by GLSP. So we opted for removing it as it serves no benefit over the GLSP Freeform layout.

As a consequence also the const STACK should be removed from `GConstants.Layout`

**Comment by planger** [comment]
@rsoika Thank you for raising this issue! Good catch! I've opened a PR.
