### ISSUE TITLE
Theia GLSP widget looses focus after using the palette

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#1088]
https://github.com/eclipse-glsp/glsp/assets/588090/bd3eec07-3937-47f4-9f2d-2ec1ec738bf0

It looks like this may be caused by the Theia Explorer widget, as it doesn't happen if the Theia Explorer widget is hidden or closed.

**Comment by tortmayr** [comment]
Good catch. It definitely seems to be related to the explorer view. Funny thing. If I close the explorer view and open it again focus handling works as expected.

**Comment by martin-fleck-at** [comment]
I believe this has to do with the point in time when we render the tool palette. In Sprotty, UI extensions remember the active element at the time they are shown to later restore focus to that element if they are hidden. For the tool palette, this results in tracking the file explorer from which the file was opened as active element and we do restore focus to that when we enable the default tools. I prepared a PR that should fix that but somebody with some focus issue experience should have a look at that ;-) https://github.com/eclipse-glsp/glsp-client/pull/278
