### ISSUE TITLE
Command Palette in 1.1.0.RC10 - wrong position of suggestion list?

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#1094]
### Discussed in https://github.com/eclipse-glsp/glsp/discussions/1093

<div type='discussions-op-text'>

<sup>Originally posted by **rsoika** August 20, 2023</sup>
Hi,
something seems to have changed with the Command Palette from RC04 to RC10 with the 

The command-palette-suggestions are now no longer placed relative to the command-palette-input. It seems the element is now positioned relative to the man window. If I change the left menue-bar than the command-palette-suggestions position also changed.

See: 

![Peek 2023-08-20 15-04](https://github.com/eclipse-glsp/glsp/assets/1339124/a35a8525-babe-4a1a-b024-ba09c3e08588)
---
I am not the expert in CSS but I think the problem is the attribute `position: absolute;` assigned to the element `autocomplete command-palette-suggestions` If I remove this attribute or change it to `fixed` it may propabyl work again correctly. But I can not really verifiy this as the component is constructed by some javascript dynamically.
</div>

**Comment by tortmayr** [comment]
This seems to be broken in sprotty as well. I think we pulled in this bug when upgrading to the latest sprotty version.

**Comment by tortmayr** [comment]
@planger I provided a fix in sprotty for this: https://github.com/eclipse-sprotty/sprotty/pull/372.

**Comment by planger** [comment]
Great, thank you @tortmayr! Already briefly tested and approved :-)
