### ISSUE TITLE
Connection problems for node-json-vscode template.

### ISSUE THREAD

**Issue by Rtulpe** [eclipse-glsp/glsp#1100]
As evident by 3 ongoing discussions (#967, #1090, #1095) there is an issue to how this template is started. We are able to reproduce this issue for:

- MacOS
- Windows 10 and partly Windows 11

It does not seem to affect Linux environments.

The issue comes from the way the server process is started -> [server process](https://github.com/eclipse-glsp/glsp-examples/blob/adfa7340a9e01d80d32b648fcfb70ee3f666f0ef/project-templates/node-json-vscode/glsp-client/tasklist-vscode/extension/src/tasklist-extension.ts#L34-L40). If you were to check the pid of the server process you would see a mismatch of IPv4 or IPv6 being used dependant on the how you launch it. Hence you would get "ECONNREFUSED" error, as you're trying to connect to the wrong address.

We have found that if you explicitly set the host ip in the socket configuration, this issue goes away:
`socketConnectionOptions: {
port: JSON.parse(process.env.TASKLIST_SERVER_PORT || DEFAULT_SERVER_PORT) ,
host: "127.0.0.1",
}`

I hope this helps in some way.

**Comment by dinkoivanov-gepard** [comment]
Thanks @Rtulpe , I applied the workaround, but the error persisted.
I think the tasklist-extension.ts gets ignored overall - tried entering some invalid host/port data and VS code did not complain, still tried to use the old port.

**Comment by Rtulpe** [comment]
Which Launch configuration are you using? If you have in env
`"TASKLIST_SERVER_DEBUG": "true"`
then my suggested changes will be ignored

**Comment by dinkoivanov-gepard** [comment]
@Rtulpe thank you, it did work when I set it to false!

**Comment by tortmayr** [comment]
Fixed in current master. Needs be retested by adopters once the 2.0.0 is released and templates have been updated.

**Comment by tortmayr** [comment]
Fixed with https://github.com/eclipse-glsp/glsp-server-node/pull/67
