### ISSUE TITLE
Windows Pathing Issues in the Workflow-Standalone Example

### ISSUE THREAD

**Issue by haydar-metin** [eclipse-glsp/glsp#1101]
The server can not open the `example1.wf` file in the [Workflow-Standalone Example](https://github.com/eclipse-glsp/glsp-client/tree/master/examples/workflow-standalone) on Windows:

Log:

```
// yarn start:exampleServer
...
15:41:15 error -  [WorkflowGLSPServer] Could not process action: 'requestModel
15:41:15 error -  [WorkflowGLSPServer] Error: Could not load model from file: /C:/Users/.../glsp-client/examples/workflow-standalone/app/example1.wf
```

It works again after removing the `/` in the `examplePath` used in https://github.com/eclipse-glsp/glsp-client/blob/master/examples/workflow-standalone/src/app.ts#L37 by hardcoding the URI in https://github.com/eclipse-glsp/glsp-client/blob/master/examples/workflow-standalone/src/app.ts#L49:

```ts
container = createContainer({ clientId, diagramType, glspClientProvider: async () => glspClient, sourceUri: 'C:/Users/.../glsp-client/examples/workflow-standalone/app/example1.wf' });
```

OS: Windows 10
Node: 16.19.1

**Comment by tortmayr** [comment]
Tested this, and the issue only appears with the node implementation. In the Java variant we convert the received url into a new `File` object. This seems to take care of proper path conversion (i.e. removal of leading slashes under Windows).
For the node-serer we don't have the same functionality. We use `the `fileUrlToPath` utility function, but that does not consider leading slashes. So we have to handle them manually.
