### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#112]
- Create matrix of which features are supported in which mode (standalone, theia, Eclipse, vscode)
- Document protocol
- Remove wiki or update to direct to the README: https://github.com/eclipse-glsp/glsp/wiki
- Update GLSP animated GIF

**Comment by martin-fleck-at** [comment]
Deleted wiki page

**Comment by planger** [comment]
@martin-fleck-at This is done, isn't it?

**Comment by martin-fleck-at** [comment]
@planger Yes it is, sorry I forgot to change the state!
