### ISSUE TITLE
Investigate focus change and selection update `onModelRootChanged`

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#1194]
See https://github.com/eclipse-glsp/glsp/discussions/1186#discussioncomment-7836755 for the origin of this issue.

We should investigate:
1. Why do we update the selection `onModelRootChanged` to an empty set? Imho this should be reconsidered if that's necessary / useful. See `SelectionService.modelRootChanged`? 
2. Why does the update of the selection impact / steel the focus as reported in the discussion linked above?

**Comment by martin-fleck-at** [comment]
I opened a PR that no longer sends a selection update when we only change the root but all the selected elements stay the same. I think this was a remnant of some older code that we no longer need. This also prevents the Theia-GLSP-Selection-Forwarder from being triggered all the time. We still do the `onModelRootChanged` -> `updateSelection` as we want to re-calculate the selection based on the new root to see if the selection can still be applied. (the empty sets just means no change and we use the previous state). As for the focus change I can no longer reproduce this, changing the selection in Theia does not change the active widget or steal focus as far as I can tell.
