### ISSUE TITLE
List<subclass> is currently not allowed in addAll method

### ISSUE THREAD

**Issue by dmm9** [eclipse-glsp/glsp#1199]
The [GModelElementBuilder.addAll() method](https://github.com/eclipse-glsp/glsp-server/blob/282656ae3f939f4f892adcaf4993dbe56eff7d7a/plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/builder/GModelElementBuilder.java#L67) should accept lists of different types, as long as it extends GModelElement.

i.e. Currently, this fails to compile:
```java
List<GNode> nodeList = new ArrayList<>();
nodeList.add(...);

parent.addAll(nodeList); // error
```

A good explanation why the Java compiler rejects `List<subclass>` as argument can be found in [this stackoveflow question](https://stackoverflow.com/questions/9319758/passing-listsubclass-to-method-expecting-listsuperclass).

It fixes by changing function signature from:
```java
public E addAll(final List<GModelElement> children)
```
to
```java
public E addAll(final List<? extends GModelElement> children)
```

**Comment by planger** [comment]
Thanks for reporting this issue! This indeed seems like an oversight. Would you be able to open a PR to fix it @dmm9? Thank you!

**Comment by dmm9** [comment]
yes I am already working on it :)
