### ISSUE TITLE
FeedbackActions are not applied after initial SetModel

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#1239]
If adopters dispatch early feedbackActions they are not applied to the inital `SetModelAction`.
Currently feedback actions are only reapplied after a model update. We should change this to also consider `SetModelAction`s.

**Comment by ivy-lli** [comment]
I'm not sure why, but this was the case on 1.0.0 that feedback actions were applied to the initial model and this is no longer the case with 2.1.0. 
But maybe there was an additional UpdateModelAction fired initially on our stack.
