### ISSUE TITLE
Glsp-Playwright repo doesn't build

### ISSUE THREAD

**Issue by dmm9** [eclipse-glsp/glsp#1262]
Steps
- Clone glsp-playwright
- `yarn` > Errors

Root causes:
1. The `examples/workflow-test` has a dependency on `"@theia/playwright": "^1.39.0"`. Currently, this pulls theia/playwright version 1.46.0, which is incompatible with glsp-playwright (braking change on TheiaApp class, which removed loadApp method).
2. rimraf command fails with `Error: Illegal characters in path`

Solutions:
1. Narrow versions of @theia/playwright. e.g. "1.39.0" or ">=1.39.0 <1.??.??"
2. Add `--glob` flag to rimraf command

**Comment by planger** [comment]
@haydar-metin Can you please take a look at this? Thank you!

**Comment by haydar-metin** [comment]
@dmm9 Thank you for the changes and the hint. We can merge your PR. After https://github.com/eclipse-glsp/glsp-playwright/pull/7 is merged, we can use the new features provided from `(Theia-)Playwright`.
