### ISSUE TITLE
Different HTML generated for standalone vs theia client

### ISSUE THREAD

**Issue by dmm9** [eclipse-glsp/glsp#1263]
Hi, I was trying to add some playwright tests to my GLSP-based project. It has taken me a couple of days to figure out why my graph class was not finding the nodes in the diagram, although the screenshots from the test reports were showing the diagram.

### Symptom
GLSP-Playwright not able to recognize even the top-level diagram elements.

### Cause (in Playwright)
The following code does not work.
``` typescript
export class GLSPGraph extends Locateable {
    static locate(app: GLSPApp): GLSPLocator {
        return app.locator.child(SVGMetadataUtils.typeAttrOf('graph')).child('svg.sprotty-graph');
    }
```
Manually substituting the locator/selector at selected places (i.e. overriding methods of GLSPGraph with hard-coded locators/selectors) yields the correct results. For example, `locator('[id="MyNodeID"]')`
So, the following code would work in my case, but it is impossible to override a static method
``` typescript
        return app.locator.child(SVGMetadataUtils.typeAttrOf('graph'));
```
### Root Cause
It seems that for the development of @eclipse-glsp/glsp-playwright the standalone example of glsp was used. Comparing the HTML code generated for standalone and theia-client versions, they are different. Note that the theia-client (see below) does not fulfil the locator above.
#### Standalone example ("Workflow"). v2.0.0
```html
<div data-svg-metadata-type=”graph”>
  <svg class="sprotty-graph">
```
![Untitled](https://github.com/eclipse-glsp/glsp/assets/11932352/23f17f43-4ed5-4cb5-9439-f45526a6b8a6)

#### My Project, using theia-glsp-client v2.0.0
```html
<svg class="sprotty-graph" data-svg-metadata-type="graph">
```
![Untitled-1](https://github.com/eclipse-glsp/glsp/assets/11932352/f9033d3a-c737-4ca4-b8ac-c84ca45a8be0)

### Possible fixes
- [ ] **Solution: Align HTML generation of all theia-clients**. Eventually, correct return value of locate() function in GLSPGraph if needed.
- [ ] **Improvement**: Make locate() function in GLSPGraph non-static, so that it can be overriden and it is easier to debug next time.
- [ ] **Bonus**: Even better: The graph-locator could be stored in a property (overrideable at instantiation). This has another positive enhancement: It enables to test applications that open more than one diagram by giving each graph instance a more accurate locator. For example providing a locator that includes the theia-tab name.

**Comment by haydar-metin** [comment]
@dmm9 Thanks for the report! The tests within [GLSP-Playwright Example](https://github.com/eclipse-glsp/glsp-playwright/tree/main/examples/workflow-test) run for the [Standalone](https://github.com/eclipse-glsp/glsp-client/tree/master/examples/workflow-standalone), [Theia Integration](https://github.com/eclipse-glsp/glsp-theia-integration) and [VSCode Integration](https://github.com/eclipse-glsp/glsp-vscode-integration) instances. 

You can override the locator for the `GLSPGraph` by overriding the following [createGraph](https://github.com/eclipse-glsp/glsp-playwright/blob/main/packages/glsp-playwright/src/glsp/app/app.po.ts#L126) method in the GLSPApp. Then pass your own locator instead of the default one. There shouldn't be a need to override the static method. As the locator comes from the outside, you should be able to fully change it. The [WorkflowApp](https://github.com/eclipse-glsp/glsp-playwright/blob/main/examples/workflow-test/src/app/workflow-app.ts) also overrides the GLSPGraph (but doesn't change the locator).
 
> It has taken me a couple of days to figure out why my graph class was not finding the nodes in the diagram, although the screenshots from the test reports were showing the diagram.

However, it seems that we need to provide more logs, so that doesn't happen again!

**Comment by haydar-metin** [comment]
> But why is the HTML tree different in WorflowApp and Theia-integration, so that theia integrations need to override the locator?

Good question, the tests provided in the glsp-playwright repository do not require a different locator and are executed correctly. I assume the used GGraph is different in your case. Could you tell me which graph you use for your client (maybe a link)? It can be, that the integrations use a modified GGraph, I will have a look at it.

**Comment by dmm9** [comment]
> Could you tell me which graph you use for your client (maybe a link)? It can be, that the integrations use a modified GGraph, I will have a look at it.

I am using GLSP v2.0.0, and I create my Graphs like this (summarized code):

```java
import org.eclipse.glsp.graph.GModelRoot;
import org.eclipse.glsp.graph.GGraph;
import org.eclipse.glsp.server.emf.EMFGModelFactory;

public class CustomGModelFactory extends EMFGModelFactory {

    @Override
    protected void fillRootElement(final GModelRoot newRoot) {

        GGraph graph = GGraph.class.cast(newRoot);

        List<Object> objects = getObjects();
        objects
            .stream()
            .map(
                object -> new CustomGNodeBuilder(object).addCssClass("custom-node").build())
            .forEachOrdered(graph.getChildren()::add);
    }
}
```

**Comment by haydar-metin** [comment]
Hey @dmm9 Thank you for the snippets!

I have found the difference:

The workflow example uses [GLSPProjectionView](https://github.com/eclipse-glsp/glsp-client/blob/master/packages/client/src/views/glsp-projection-view.tsx#L40) for the [GGraph](https://github.com/eclipse-glsp/glsp-client/blob/master/examples/workflow-glsp/src/workflow-diagram-module.ts#L78) while you are using [GGraphView](https://github.com/eclipse-glsp/glsp-client/blob/154edf18baa1b1eadcaf92946986562d11d2de32/packages/client/src/views/base-view-module.ts#L76). The former creates the views differently. Thank you for highlighting it! We should also handle this case.

**Comment by haydar-metin** [comment]
@dmm9 the referenced PR should now remove the not required implementation detail of the GLSPGraph locator and also provide some references on how to debug. Thank you very much for raising the issue.
