### ISSUE TITLE
Handle reconnect using socket-based GLSP servers

### ISSUE THREAD

**Issue by ndoschek** [eclipse-glsp/glsp#1277]
Follow-up of https://github.com/eclipse-glsp/glsp/issues/77

Ensure reconnect handling is properly implemented for the socket-based GLSP servers
- restoring client connections and client sessions after reconnects/interrupts

**Comment by planger** [comment]
@ndoschek Can this be closed as the PR is merged? Thanks!

**Comment by ndoschek** [comment]
Hi @planger, unfortunately not, as this is the follow-up of the initial issue. We did not provide a fix for socked-based GLSP servers yet, only for the websocket variants.

**Comment by ndoschek** [comment]
Ah thanks @tortmayr  for refreshing my mind, yes then let's close it :+1:
