### ISSUE TITLE
Change RequestMarkersAction / SetMarkersAction to be a request-response pair

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-glsp/glsp#129]
Both actions are simple actions even though they should be a request-response pair. The main reason for that not being the case is that they have been implemented before request-response handling was available. The way those tools are currently used, we probably need to implement a 'validation tool' to avoid having the tool palette having to trigger the RequestMarkersAction directly.

**Comment by martin-fleck-at** [comment]
It seems that the 'SetMarkersAction' can be sent from the server at any point in time, so they are not actually a request-response pair. So the issue now is that responses without requests are not delegated normally on the client side but instead they are logged as an error.

**Comment by planger** [comment]
Should we therefore close this issue as this can't really be a request/response pair?

**Comment by martin-fleck-at** [comment]
Yes, that is fine by me. If anything in this regard comes up again, we can create a new issue.
