### ISSUE TITLE
Add electron application example to theia-integration

### ISSUE THREAD

**Issue by ndoschek** [eclipse-glsp/glsp#1303]
- Add electron application example to the GLSP theia-integration repository
- Add the same application versions as for the browser version (i.e. WS GLSP Server, integrated node server etc.)
- Provide yarn scripts and launch configs for all combinations
- Ensure rebuild scripts are run prior to starting the application examples (via yarn script or VS Code task for launch configs)
- Do not build electron application by default, but provide scripts to build from the root directory on demand
- Provide description in the README

There is already a WIP branch available that contains the first basic electron application example:
https://github.com/eclipse-glsp/glsp-theia-integration/tree/issues/1303

**Comment by tortmayr** [comment]
Resolved with https://github.com/eclipse-glsp/glsp-theia-integration/pull/211
