### ISSUE TITLE
Troubleshooting TypeHint feature in GLSP Framework

### ISSUE THREAD

**Issue by EightM** [eclipse-glsp/glsp#1309]
Given: Java GLSP server 2.1 + GLSP client 2.1.1

After upgrading from version 0.9 to version 2.0, the TypeHint feature broke: requests RequestTypeHintsAction stopped coming to the server.
Analysis showed that in the code of glsp-client there is a method `DiagramLoader.load`. It contains a call to hooks, and the RequestTypeHintsAction request should occur within the "postRequestModel" hook.

At the time DiagramLoader.load is executed, there are two "postRequestModel" hooks in `this.diagramStartups`: TypeHintProvider and RestoreViewportHandler. The hook from RestoreViewportHandler is executed first.

It expects an element with a hardcoded selector: `'[data-svg-metadata-type="graph"]'`. If such an element is missing, this hook does not complete (?) and the hook from TypeHintProvider is not executed. Consequently, the RequestTypeHintsAction request is not executed.

The problem was that in my implementation on the server side, there is a custom ModelLoader (CustomModelLoader implements SourceModelStorage). And it overrides the diagram type:

`myGGRAPH.setType("MyGraphType");`

After I got rid of the model type change, RequestTypeHintsAction requests started coming successfully.

What I would like to expect from the GLSP framework itself:

- It seems that the failure of one hook should not affect the execution of another hook.

- If changing the type of GModelElement can break the model initialization process, it might be worth mentioning this in the documentation.

- If a hook fails for any reason, it would be useful to write about it in the logs (perhaps it is written, but I did not find it).

**Comment by planger** [comment]
Thank you for your bug report! We indeed should catch errors during the startup to complete the startup process and then report potential errors once the startup is completed. We put this in our backlog with high priority. If you happen to be able to contribute a fix, we'd be very happy to review too. Thank you!

**Comment by tortmayr** [comment]
Fixed with https://github.com/eclipse-glsp/glsp-client/pull/346
