### ISSUE TITLE
Consider future of ExecuteServerCommandAction

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-glsp/glsp#131]
The `ExecuteServerCommandAction` is sent from the client to the server to invoke the execution of a server command. Server commands may execute arbitrary actions, such as code generation, etc. These actions, however, shouldn't manipulate the model.

We currently do not have a use case for it and there is no corresponding operation for it that allows model manipulation. We either should remove this action from our protocol or provide a corresponding operation.

In my opinion our extension mechanism is to create new actions so having such a generic action is not really necessary but I open that for discussion.

**Comment by tortmayr** [comment]
@martin-fleck-at  Can we close this?

**Comment by martin-fleck-at** [comment]
Yes, absolutely, sorry for missing it!
