### ISSUE TITLE
Required Node version for minimal example

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-glsp/glsp#135]
https://github.com/eclipse-glsp/glsp-examples

requires ">=10.19.0 <13" Node version

is this necessary or can we go done to include more users...

**Comment by planger** [comment]
This is a prerequisite of Theia. In the meantime, Theia even only supports node 12. So imho we should even update that to reflect the dependencies of Theia.
https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites

**Comment by JonasHelming** [comment]
makes sense
