### ISSUE TITLE
Readme for Workflow example and integrations

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-glsp/glsp#136]
Add this section in the wiki of all relevant components: Eclipse, Theia, VS Code, client (standalone), GLSP server
https://github.com/eclipse-glsp/glsp-theia-integration
https://github.com/eclipsesource/glsp-vscode-integration
https://github.com/eclipsesource/glsp-eclipse-integration
https://github.com/eclipse-glsp/glsp-client (standalone)

# Workflow Diagram Example => dont change this heading, cause it is an anchor
The workflow diagram is a consistent example provided by all GLSP components. The example implements a simple flow chart diagram editor with different types of nodes and edges (see screenshot below). The example can be used to try out different GLSP features, as well as several available integrations with IDE platforms (Theia, VSCode, Eclipse, Standalone).
As the example is fully open source, you can also use it as a blueprint for a custom implementation of a GLSP diagram editor.
See [our project website](https://www.eclipse.org/glsp/documentation/#workflowoverview) for an overview of the workflow example and all components implementing it.

=>Add animated Gif of the respective example

## How to start the Workflow Diagram example?
=>if client: You use this workflow diagram example client, you will also need the [workflow example diagram server](https://github.com/eclipse-glsp/glsp-server#workflow-diagram-example)

=>Instructions how to launch the example

=>if server: To see the diagram in action, you will need to choose and launch one diagram client, see [here for an overview](https://www.eclipse.org/glsp/documentation/#workflowoverview).

## Where to find the sources?
Instructions on where to find the sources

**Comment by JonasHelming** [comment]
@planger : Please review the above before rolling out

**Comment by JonasHelming** [comment]
And to the main wiki just the first paragraph

**Comment by planger** [comment]
Thanks, yes looks good to me!

Some minors:

The workflow diagram is a consistent example provided by all GLSP components. The example implements a simple flow chart diagram editor with different types of nodes and edges (see screenshot below). The example can be used to try out different GLSP features, as well as several available integrations with IDE platforms (Theia, VSCode, Eclipse).
As the example is fully open source, you can also use it as a blueprint for a custom implementation of a GLSP diagram editor.
See our project website for an overview of the workflow example and all components implementing it.

I assume in "Where to find the sources?" we point to the client-core, server, and integrations, right?

:+1:  Great, thanks a lot!

**Comment by JonasHelming** [comment]
I updated the first description based on your feedback!

Where to find the sources: Just point to the directory in the respective directory where the example code is (typically /examples/workflow). No need to point to client-core...

**Comment by JonasHelming** [comment]
Can we get this done before Christmas please?

**Comment by ndoschek** [comment]
For `@eclipse-glsp/glsp-eclipse-integration` is now a GIF of the workflow example editor available at https://github.com/eclipse-glsp/glsp-eclipse-integration/blob/master/documentation/glsp-eclipse-integration-animated.gif.

**Comment by CamilleLetavernier** [comment]
@JonasHelming the "See our project website" link points to https://www.eclipse.org/glsp/documentation/#workflowoverview, which doesn't seem to exist (The page exists, but the anchor doesn't). Also, that documentation page points to the old repository for Ecore GLSP (The correct one is now https://github.com/eclipse-emfcloud/ecore-glsp)

**Comment by JonasHelming** [comment]
@CamilleLetavernier The #workflowoverview section is available on a branch already:
https://github.com/JonasHelming/graphical-lsp-website/tree/GH-12
I will push this, once the docu is ready...

The secon part I am not sure I understand, what is there relation to the theia ecore editor?

**Comment by CamilleLetavernier** [comment]
> The secon part I am not sure I understand, what is there relation to the theia ecore editor?
I mean that this page: https://www.eclipse.org/glsp/documentation contains a link to the "Ecore Editor" in the Examples section. The link points to the old repository of the Ecore Editor (https://github.com/eclipsesource/ecore-glsp instead of the new https://github.com/eclipse-emfcloud/ecore-glsp)

**Comment by JonasHelming** [comment]
https://github.com/eclipsesource/graphical-lsp-website/pull/13

**Comment by JonasHelming** [comment]
> > The secon part I am not sure I understand, what is there relation to the theia ecore editor?
> 
> I mean that this page: https://www.eclipse.org/glsp/documentation contains a link to the "Ecore Editor" in the Examples section. The link points to the old repository of the Ecore Editor (https://github.com/eclipsesource/ecore-glsp instead of the new https://github.com/eclipse-emfcloud/ecore-glsp)

OK, but this is unrelated to this, right? I created a separated issue: https://github.com/eclipsesource/graphical-lsp-website/issues/14

**Comment by CamilleLetavernier** [comment]
> OK, but this is unrelated to this, right?

Yes; it's just an issue I noticed while testing the link :)

**Comment by planger** [comment]
So I think I've reviewed and merged all changes. Please note that I changed the instructions on starting the server quite a bit:
I now always first mention to start the server from the command line after building, to avoid having users to set up an IDE first and then mention that they can also import the sources in their IDE and start the respective Java class.
I also tried to centralize that on the glsp-server readme, where it made sense.
I also tested all the steps again.

**Comment by planger** [comment]
@JonasHelming @CamilleLetavernier Please double-check the readmes again to make sure they are as you think they should be after those changes.
