### ISSUE TITLE
Minimal example, build failing

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-glsp/glsp#137]
Please add steps to launch the minimal example in the readme

Please replace screenshot (animated gif)

Further, build is failing, npm and maven not build
https://github.com/eclipse-glsp/glsp-examples

**Comment by tortmayr** [comment]
@JonasHelming I'm going to fix the build error, but just as an FYI: We currently have no plans of deploying nightly/next snapshots to npm/maven for this example repository. Only actual releases are going to be deployed. Is this fine for your you or do you explicitly need nightly deployment?

**Comment by JonasHelming** [comment]
That is fine!

**Comment by martin-fleck-at** [comment]
Did not want to close this as part of it still needs to be done:
- [ ] Update GIF in README

**Comment by JonasHelming** [comment]
Can we get this done before Christmas please?
