### ISSUE TITLE
Examples repository does not contain the workflow example anymore

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-glsp/glsp#138]
Only "minimal" is available, but workflow is mentioned, e.g. here:
https://github.com/eclipse-glsp/glsp#building-and-starting-the-workflow-example

**Comment by planger** [comment]
Ah good catch, we missed to update the docs after the extraction of the example and creation of the minimal example.

**Comment by JonasHelming** [comment]
Should be fixed along with #136 the solution is mentione in a omment in #136

**Comment by JonasHelming** [comment]
Can we get this done before Christmas please?
