### ISSUE TITLE
[Playwright] Some E2E test fails when using java workflow server

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#1383]
Details: https://github.com/eclipse-glsp/glsp-playwright/actions/runs/10076706620/attempts/1#summary-27857630888

Java tests have been deactivated for now and should be reactivated once this is fixed.

In particular it seems that the context menu and popup tests are affected by this

**Comment by planger** [comment]
Check if it is something that can be easily fixed (e.g. undefined <> null). If there are really different behaviors, we can reconsider skipping certain tests depending on the effort.
