### ISSUE TITLE
Multiple DefaultActionDispatcher are created and not properly disposed

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-glsp/glsp#1387]
Steps to reproduce:
- Start the Java server and the standalone example
- There is a temporary client session for each diagramType created to retrieve the diagram type specific
- Check that there are two action dispatcher threads created
- Reload the page
- See that one action dispatcher thread remains and two new are created
- Continue to see the number of remaining action dispatcher threads rising

![image](https://github.com/user-attachments/assets/665df8af-be9a-4198-a69b-b3fc4f5d3c8f)

It seems to me that the problem is that the action dispatcher also serves as an action handler for the internal `JoinAction`. The multi-binding does not ensure that we re-use the existing action dispatcher which would be achievable through a provider binding or other methods.

**Comment by ivy-lli** [comment]
PR: https://github.com/eclipse-glsp/glsp-server/pull/246
