### ISSUE TITLE
Migrate javas server and eclipse integration to jarkata

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#1397]
https://jakarta.ee/blogs/javax-jakartaee-namespace-ecosystem-progress/

Currently the java base component still rely on outdated javax dependencies. This is an issue because it forces us to use old and potentially outdated versions of third-party dependencies and blocks easy integration of GLSP into current Eclipse releases.

Therefore we should properly migrate to the new jarkata namespace and update all related plugins and packages.
Unfortunately this is inevitably a breaking change.

**Comment by ivy-lli** [comment]
Hi @tortmayr, @martin-fleck-at 
Is this planned for the next v2.3 update? Because I think this could break some setups.
At least in our case, I think it could be a little bit difficult to integrate it. 

We definitely want to update on Jakarta too, but this is a heavy process on our side.
Can you postpone this PR to v2.4?

**Comment by tortmayr** [comment]
Hi @ivy-lli,
yes this is planned to be part of the v2.3 update.
However, we are aware that this could potentially break some setups.
Therefore we have decided to make the 2.3 release a dual release and we will publish
updatesites for both the new jarkarta based variant as well as the old javax based solution.
So you can then simply consume the javax based version.

Currently it is planned that starting with 2.4 we will only maintain the jakarta based version.

**Comment by ivy-lli** [comment]
Perfect thanks 👍

**Comment by ivy-lli** [comment]
Hi @tortmayr 

As a saw you have released v2.3.0, congratulations 🎉 
I already updated our clients to this version and didn't saw any problems yet 👍 

I also saw that you created new releases for the server and the eclipse-ide, but currently only the ones with the jakarta dependencies. Do you have already a date for the old javax versions?

**Comment by martin-fleck-at** [comment]
Hi @ivy-lli 

Glad you didn't encounter any problems so far! We need to do the `javax` release manually and will do so within the next few days, so stay tuned!

**Comment by tortmayr** [comment]
@ivy-lli 
The javax backport for 2.3.0 is now available:

https://download.eclipse.org/glsp/server/p2/releases/2.3.0.javax
https://download.eclipse.org/glsp/ide/p2/releases/2.3.0.javax

**Comment by ivy-lli** [comment]
Thanks a lot 🎉 
I've already updated on it, and it seems to work without any problems ❤️
