### ISSUE TITLE
Weighted edges cannot be created anymore

### ISSUE THREAD

**Issue by haydar-metin** [eclipse-glsp/glsp#1401]
The weighted edges can not be created anymore.

1. Select `Weighted Edge` from the tool palette
2. Selecting a `Decision Node` / `Fork Node` is not possible.

![image](https://github.com/user-attachments/assets/60c15f2d-7e20-4ba0-a229-24dd1ed3078b)

Related: https://github.com/eclipse-glsp/glsp-playwright/pull/23

**Comment by tortmayr** [comment]
Works for Java server. Bug is node specific
