### ISSUE TITLE
Get standalone working in a docker environment

### ISSUE THREAD

**Issue by holkerveen** [eclipse-glsp/glsp#1410]
Hi all in the glsp project!

**edit** this is mostly related to [glsp-client](https://github.com/eclipse-glsp/glsp-client)

### Problem
I have been trying out the glsp packages to see if it could be a good fit for me wanting a flowchart like editor in one of my projects. Really like what I'm seeing so far! BUT I had a hard time getting a node-json-standalone setup working in a docker setup. I eventually:
1. hacked the `bundle.js` to change the `example1.wf` path so that would load
2. I added a `--host 0.0.0.0` parameter to the node call in `start-example-server.ts`
Another thing that I encountered is that the deducing the example file path based on `window.location` does not work if the path is in any way modified. For example, when I open the `index.html` file in PhpStorm, it gets opened in some kind of dev server which modifies the `window.location.pathname`

### Proposed solution
I would like to add the hacks I did to get it working in the repository proper:
1. Adding a command line option to the client app so that one could specify an example filepath different from the one that is now inferred. With current setup as a default of course
2. Adding configurable _port_ and _host_ parameters to start-example-server.ts
3. Modifying the `package.json` files to allow passing these _port_ and _host_ parameters

Would it also be helpful if I were to add a Dockerfile to run the example and a reference to that in the readme?

**Comment by tortmayr** [comment]
Hi @holkerveen,
sorry for the late reply.

Currently we don't have any plans to provide and/or maintain docker files with our repositories.
However, we would appreciate a PR contribution that enables the configuration of the `port` and `host` parameters.
