### ISSUE TITLE
Move element out of window and then to a invalid location don't reset the move feedback

### ISSUE THREAD

**Issue by ivy-lli** [eclipse-glsp/glsp#1426]
If an element is dragged out of the window and then is placed on an invalid position, the MoveFeedback is not correctly reset.
But also only if you click on the invalid area (see workflow example where the last click is on the other element).

Strangely if the new position is valid then everything seems to work.

our glsp editor (no placement in the negative area):
![Screen Recording 2024-11-21 at 13 01 32](https://github.com/user-attachments/assets/7422c968-3bed-4a8c-828e-8c84c45239d4)

glsp workflow example with enabled NoOverlapMovementRestrictor:
![Screen Recording 2024-11-21 at 13 02 48](https://github.com/user-attachments/assets/5cfc8695-2851-4661-9221-833786672af5)

Honestly not sure how I can fix this. Maybe you have an idea here @martin-fleck-at?

**Comment by martin-fleck-at** [comment]
From what I can see this is actually a feedback issue as another operation properly resets the element to the correct position. I can reproduce this by dragging the mouse outside the window, releasing the mouse button and then clicking on another element. When a selection occurs, we are stuck, is that the same behavior for you? If so, I can have a look at it, we probably just need to listen to the selection in the feedback listener and dispose the feedback.

**Comment by ivy-lli** [comment]
I'm not 100% sure why this happens... 
What I saw is that in the [`FeedbackMoveMouseListener` (change-bounds-tool-move-feedback.ts)](https://github.com/eclipse-glsp/glsp-client/blob/master/packages/client/src/features/tools/change-bounds/change-bounds-tool-move-feedback.ts#L73-L78) the initialMove (which is triggered by the mouseDown) can not find an moveable element and because of this stop the tracker.

**Comment by martin-fleck-at** [comment]
@ivy-lli True, I can also see that being triggered _sometimes_. I tried a fix in https://github.com/eclipse-glsp/glsp-client/pull/399, maybe you have some time to look at it and double check whether it also works for your use case.

**Comment by ivy-lli** [comment]
Quickly checked our impl with the [@eclipse-glsp/client@2.3.0-next.390](https://www.npmjs.com/package/@eclipse-glsp/client/v/2.3.0-next.390). Seems to work. Thanks 👍 
![Screen Recording 2024-11-25 at 13 26 08](https://github.com/user-attachments/assets/33103fac-3663-4d49-9c07-2948d15e021e)
