### ISSUE TITLE
TypeError: this.rankedMouseListeners is not iterable

### ISSUE THREAD

**Issue by QiUser7** [eclipse-glsp/glsp#1428]
Hello, I currently use GLSP version 2.2.1, the workflow example through their own changes, an error: this. RankedMouseListeners is not iterable. I can't pinpoint the specific cause of the error, and I can't fix it. Please help me.

**Comment by QiUser7** [comment]
resolved

**Comment by tortmayr** [comment]
Hi @QiUser7,

we cannot really help you without additional information like the  error stack trace and/or more details about the change which caused the error.

In general it looks like the issue occurs in the [GLSPMouseTool](https://github.com/eclipse-glsp/glsp-client/blob/670e160fa44564cbe7921643ff5d02357276b117/packages/client/src/base/view/mouse-tool.ts#L28)

However, the `rankedMouseListeners` property is a Map so it definitively should be iterable.
Maybe something goes wrong when the rankedListeners are recomputed
You could try to debug into the [register()](https://github.com/eclipse-glsp/glsp-client/blob/670e160fa44564cbe7921643ff5d02357276b117/packages/client/src/base/view/mouse-tool.ts#L37) method.
