### ISSUE TITLE
Context(model) sensitive tool palette.

### ISSUE THREAD

**Issue by akera-io** [eclipse-glsp/glsp#1432]
The current tool palette is loaded through the RequestContextActions, this is fine only it is done before loading the model and there is no information about the model/document that is going to be loaded when the palette is created.

We are trying to support multiple model 'dialects' and some palette items are specific to said dialects, it would be great if we could adapt the palette based on the document model dialect.

If possible best will be to have the palette loaded after the RequestModelAction so the model state is available.

If the request order can't be changed is there a way to have the `sourceUri` added as argument to the RequestContextActions for tool palette?

**Comment by tortmayr** [comment]
Hi @akera-io,
we recently changed this behavior and moved the requesting of the tool palette actions into the `postModelInitialization` phase
(https://github.com/eclipse-glsp/glsp-client/pull/398). The main reason for this change was to avoid potentia blocking/delaying of the initial model loading but it indirectly also enables your use case.

This change will be available with the 2.3 release which is scheduled for early december. We are currently in the release finalization phase and expect that the release will be available within in the next two weeks.

**Comment by akera-io** [comment]
Great news Tobias, looks like sometime we just get lucky :)
Will give that a try when available, thanks.
