### ISSUE TITLE
Improve external navigation support through dedicated action

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-glsp/glsp#153]
At the moment we use a dedicated `ExternalNavigateToTargetHandler` class to handle external navigation when a navigation target cannot be resolved or is outside the scope of the resource. Using such a handler, however, imposes some limits on the navigation framework. The main drawback is that we cannot support external navigation through the server easily. I therefore propose to replace the external handler with a `NavigateToExternalTargetAction` and handle the action like any other action (client or server).

**Comment by tortmayr** [comment]
@martin-fleck-at  Can this be closed?

**Comment by martin-fleck-at** [comment]
Yes, all related PRs have been merged, thank you!
