### ISSUE TITLE
[Eclipse] Handlers are invoked multiple times

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#160]
When using Keybindings to trigger commands, the handlers may be invoked multiple times.

The affected actions are: Undo, Redo, Save and Export Diagram
These actions are triggered only once, as expected: Select All, Copy, Cut, Paste

The surprising thing is that all these actions are declared and implemented in the same way (Most of them are standard Eclipse UI Edit actions; but one is a custom action that is also affected by this bug).

**Comment by martin-fleck-at** [comment]
@tortmayr Are you experiencing this with the default browser or with Chromium? In Chromium I had the problem that no keybindings were triggered at all and I had to add a workaround, see https://github.com/eclipse-glsp/glsp-eclipse-integration/pull/6

**Comment by tortmayr** [comment]
Originally reported by @CamilleLetavernier  (https://github.com/eclipsesource/glsp-eclipse-integration/issues/10).
So we have to ask him :wink:

**Comment by CamilleLetavernier** [comment]
I used the default browser. On Chromium, I also don't get keybindings at all.

Since the default browser is now broken (#159), I can't test it anymore

**Comment by planger** [comment]
This is only a problem that we've observed with the default browser, which we don't want to support anymore, see #159
