### ISSUE TITLE
[Eclipse] Remove unnecessary scroll bars in Workflow Editor Example

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#165]
Improve css/diagram.html files of web app to avoid the unnecessary scrollbars in the editor.
![Screenshot from 2020-12-15 12-02-48](https://user-images.githubusercontent.com/2311075/102206839-807fa980-3ecd-11eb-87d4-44c3c9e28526.png)

**Comment by tortmayr** [comment]
@ndoschek Isn't this already fixed?

**Comment by ndoschek** [comment]
Yes, that was fixed with https://github.com/eclipse-glsp/glsp-eclipse-integration/pull/19
