### ISSUE TITLE
Add download script for server in stand-alone example

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-glsp/glsp#171]
There should be a simple way to download the compiled server via maven and start it for trying out the example (like for the Theia integration). I will do a contribution.

**Comment by JonasHelming** [comment]
https://github.com/eclipse-glsp/glsp-client/pull/99

**Comment by JonasHelming** [comment]
@planger : Could you let me know, if you like this (readme and script). If yes, I would do it consistently for all integrations

**Comment by planger** [comment]
Thanks a lot @JonasHelming! I like this script very much and think it would be great to add it in the theia, VSCode and Eclipse integration repos! Thank you!
