### ISSUE TITLE
Update examples when releasing a new example server

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-glsp/glsp#173]
I will collect the artifacts in this ticket, which depend on the version number of the maven deploy of the workflow example server. Either we need another technical solution (e.g. a "latest" version) or a process to update all depending clients when releasing a new server version.

https://github.com/eclipse-glsp/glsp-theia-integration/blob/master/examples/workflow-theia/server/download.ts
https://github.com/eclipse-glsp/glsp-theia-integration/blob/master/examples/workflow-theia/src/node/workflow-glsp-server-contribution.ts
https://github.com/eclipse-glsp/glsp-client/blob/master/examples/workflow-glsp/scripts/download.ts

**Comment by planger** [comment]
Thanks, I've added this step to our internal release process for now.

**Comment by JonasHelming** [comment]
Another occurence:
https://github.com/eclipsesource/glsp-vscode-integration/blob/master/example/workflow/scripts/download.ts

**Comment by planger** [comment]
@tortmayr  Can you please update our internal release process task with the links collected by @JonasHelming?
After that we can close this issue. Thanks!
