### ISSUE TITLE
GSLP code generation

### ISSUE THREAD

**Issue by chaaridev** [eclipse-glsp/glsp#185]
Hi,
I am new to EMF and GLSP.
Can I use GLSP (Eclipse Graphical Language Server Platform) to generate code in python or javascript/typescript?
If yes, can please point me to which eclipse library/framework I can use and share a few examples with me if availble.

I found these EMF/Ecore code generators online but I would like to know which ones you recommend :
 
Eclipse acceleo
https://www.eclipse.org/acceleo/
typescript:
https://github.com/crossecore/ecore-typescript
python
https://github.com/pyecore/pyecore

Thank you.

**Comment by planger** [comment]
Hi @chaaridev ,

yes sure, on the server you can use any existing framework to generate code from either the GModel directly or from the original model source that you use to create the GModel from.

We often use [Xtend](https://www.eclipse.org/xtend/) for Code generation in Java-based servers, but really anything should do that allows you to write strings into files. The code generation part is also quite independent from GLSP. In the end you just need to read either the GModel or your original model source and write files from it.

An example for a generator written in Java (and generating Java code) can be found e.g. here:
https://github.com/eclipse-emfcloud/coffee-editor/tree/master/backend/plugins/com.eclipsesource.workflow.generator.java

I hope this helps!

**Comment by chaaridev** [comment]
@planger Thank you for your quick reply and for the example that you shared. I will check it and keep reading about this.

If other developers have experience with using python or javascript/typescript EMF code generator or know of a good example, I will appreciate it.
Thank you.
