### ISSUE TITLE
Embedding LSP based text Editor in GLSP based diagram editor for label editing

### ISSUE THREAD

**Issue by kuldeeparora89** [eclipse-glsp/glsp#187]
Hi,
Is there any way we can embed LSP based text editor while editing label on GNode ?Below mentioned is the detailed use case :
We have created two extension in theia -
1.Graphical editor using GLSP to create flow diagram for our use case.
2.New language support for our DSL using Xtext LSP .
Now while using graphical editor we want end-user to enter some expression on the nodes of the diagram , semantics of which will be based on our DSL language . To assist the end-user in writing these expressions we want to provide the expression editor within the node of a diagram with features like content-assist , error highlighting etc . If we are able to embed LSP based editor then all these functionalities of LSP editor will be available out-of-the-box.
Something similar to this exists in eclipse sirius with Xtext integration-
https://altran-mde.github.io/xtext-sirius-integration.io/userguide/

**Comment by tortmayr** [comment]
Answered here: https://spectrum.chat/glsp/general/embedding-lsp-based-text-editor-in-glsp-based-diagram-editor~c6555c1b-9e15-4d6a-936a-296c1c61f003
