### ISSUE TITLE
Investigate the model revision feature on server side 

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#19]
This feature seems currently not or only partially implemented and causes a lot of issues if a concrete implementation tries to use it.

Most of these issues are related to inconsistencies between the revision state held in memory by the server and the actual model revision.

[migrated from https://github.com/eclipsesource/graphical-lsp/issues/283]

**Comment by tortmayr** [comment]
@planger I think we can close this. With the lates changes of the `ModelSubmissionHandler` and the revision is now correctly set and updated on each server update. Any objections?

**Comment by planger** [comment]
Yes, that's right. We've fixed it with the changes on the model submission handler. Thanks!
