### ISSUE TITLE
Support adding arguments to SModelElements

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#194]
We encountered a few scenarios where we would like to add data to the GModel, but extending GModel types seemed as an overkill for those use cases. Instead, it would be more convenient to just have an arguments map for elements to transfer certain information from the server to the client.

**Comment by tortmayr** [comment]
@planger  Can we close this? I think this is already merged

**Comment by planger** [comment]
Right, all is done in this regard. Thanks!
