### ISSUE TITLE
Rework workflow-example

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#220]
The workflow example implemented is rather outdated in certain ways and we should rework parts of it.
- We are currently using custom views and model types only for the purpose of applying additional css classes. This can be easily also achieved by using the `SModelElement.cssClasses`
- The size of fork and join nodes is hardcoded and therefore they are not resizable.

And probably a lot of other potential improvements  that I missed

**Comment by planger** [comment]
@lucas-koehler Can you please take over this task and then apply it to the coffee editor as well? @tortmayr can give you more details and support if needed.

**Comment by lucas-koehler** [comment]
@planger Alright, I'll start with this sometime this month
