### ISSUE TITLE
GLSP editor not working in Theia  when launched using VScode backend config

### ISSUE THREAD

**Issue by kuldeeparora89** [eclipse-glsp/glsp#221]
Hi,

I need to debug some backend code, therefore I am launching the Theia instance using Vscode launch config. But  GLSP editor is not working when launched using VSCode config, whereas it works fine when I start Theia using standalone script "yarn start".
My VSCode extensions are working fine in both modes.

Also, none of the breakpoints on the GLSP code is getting hit.

launch.json -

```
{
          "type": "node",
          "request": "launch",
          "name": "Launch Browser Backend 2",
          "program": "${workspaceRoot}/browser-app/src-gen/backend/main.js",
          "args": [
            "--hostname=0.0.0.0",
            "--port=3000",
            "--no-cluster",
            "--debug",
            "--app-project-path=${workspaceRoot}/browser-app",
            "--plugins=local-dir:${workspaceRoot}/browser-app/plugins",
            "--hosted-plugin-inspect=9339"
          ],
          "env": {
            "NODE_ENV": "development"  
          },
          "sourceMaps": true,
          "outFiles": [
            "${workspaceRoot}/browser-app/src-gen/**/*.js",
            "${workspaceRoot}/browser-app/lib/**/*.js",
            "${workspaceRoot}/node_modules/@theia/*/lib/**/*.js",
            "${workspaceRoot}/node_modules/@eclipse-glsp/*/lib/**/*.js",
            "${workspaceRoot}/mamba-table-rule-glsp-editor/lib/**/*.js"
          ],
          "smartStep": true,
          "internalConsoleOptions": "openOnSessionStart",
          "outputCapture": "std"
        }
```
I am running the GLSP server as a standalone process therefore passing "--debug" in args.
I have configured 5007 as the default port in the code, therefore not passing in arguments - 

```
 createLaunchOptions(): Partial<JavaSocketServerLaunchOptions> {
        return {
            jarPath: JAR_FILE,
            additionalArgs: ["--consoleLog", "false",
                "--fileLog", "true",
                "--logDir", SERVER_DIR],
            serverPort: getPort(PORT_ARG_KEY, DEFAULT_PORT)
        };
```

I can see the below message in Chrome dev tools -

```
Uncaught (in promise) Error: JsonrpcGLSPClient is not ready yet
    at TheiaJsonrpcGLSPClient.push.../node_modules/@eclipse-glsp/theia-integration/node_modules/@eclipse-glsp/protocol/lib/jsonrpc/base-jsonrpc-glsp-client.js.BaseJsonrpcGLSPClient.checkConnectionState (33.bundle.js:16450)
    at TheiaJsonrpcGLSPClient.push.../node_modules/@eclipse-glsp/theia-integration/lib/browser/theia-jsonrpc-glsp-client.js.TheiaJsonrpcGLSPClient.checkConnectionState (33.bundle.js:15630)
    at TheiaJsonrpcGLSPClient.push.../node_modules/@eclipse-glsp/theia-integration/node_modules/@eclipse-glsp/protocol/lib/jsonrpc/base-jsonrpc-glsp-client.js.BaseJsonrpcGLSPClient.sendActionMessage (33.bundle.js:16444)
    at 33.bundle.js:12887
```

Please let me know what could be the issue? Thanks !!

**Comment by lforst** [comment]
Hi, I am not a maintainer of the theia integration project but ran into a similar issue in the vscode integration. The problem there was that the server was not started by the extension. (Reason being, it didn't download successfully because the target folder was not created yet)  
  
I recommend you either look into the installation/download script for the server or just try to start the server manually for the time being.
  
If any maintainers are reading this: I opened a MR to fix this issue in the vscode integration. You can find it here: https://github.com/eclipse-glsp/glsp-vscode-integration/pull/2

**Comment by kuldeeparora89** [comment]
Hi @lforst ,

In my case i am already running GLSP server manually in a standalone process , see “--debug” argument in args.

**Comment by kuldeeparora89** [comment]
I found a workaround by setting "NODE_PRESERVE_SYMLINKS" to 1 under env section of launch.json -

 "env": {
            "NODE_ENV": "development",
            **"NODE_PRESERVE_SYMLINKS": "1"**  
          }

GLSP editor is now opening up & breakpoints are also working. But I am not sure how it works.

**Comment by planger** [comment]
Thanks for sharing the workaround.
We may want to add this to the readme or some other resource?
