### ISSUE TITLE
Setup deployment for vscode integration

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#244]
The vscode integration artifacts are currently not published. We should implement a deployment job for changes on master similar to how we do it in the other repositories.

We need nightly deployment of glue code packages the npm organization. (@eclipse-glsp/vsocde-integration, @eclipse-glsp/vscode-integration-webview'.

In addition, it would also be nice to publish the workflow-example vscode extension to the [Open VSX registry](https://open-vsx.org/). We have to investigative if nightly deployment is suitable here, or if we rather should implement a milestone/rc strategy for this.

**Comment by debovema** [comment]
Hi @tortmayr

Is there any status on this issue ? Any help needed ?

**Comment by tortmayr** [comment]
Hi  @debovema,
thank you for your interest. To my knowledge currently nobody is working on this issue. Unfortunately we cannot ask the community for help on this because we need to setup corresponding Jenkins Jobs which requires committer credentials.

I will prioritize this issue and hopefully we will be able to finish this in the first half of July.

**Comment by tortmayr** [comment]
The nightly deployment has been setup. The integration packages can now be cosumed via npm:

https://www.npmjs.com/package/@eclipse-glsp/vscode-integration-webview
https://www.npmjs.com/package/@eclipse-glsp/vscode-integration

Publishing of the workflow example to open-vsix is not setup yet. This will be postponed for now, and revisited once there is a need for publishing the example.

**Comment by debovema** [comment]
Thanks a lot ! I will test this ASAP

**Comment by debovema** [comment]
It works like a charm 👍
