### ISSUE TITLE
How to handle "contributors"/<developers>" lists in package.json/pom.xml

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#246]
Raised in the discussion in https://github.com/eclipse-glsp/glsp-theia-integration/pull/77#pullrequestreview-667538724:

```json
 "contributors": [   
  {    
    "name": "Tobias Ortmayr",      
    "email": "tortmayr@eclipsesource.com",     
    "url": "https://www.eclipsesource.com"    
  }  
]
```

@planger 
I'm wondering whether we should either add all committers or no one here?

 
@tortmayr 
Actually that's something I wanted to discuss in the next meeting. IMO it is quite tedious to maintain a list of all committers here. However, omitting it entirely might also be contra productive because it we probably need this list for sponsored and/or external contributions.
So I'd propose that we initially only list the package creator here. External contributors are free to extend this list.
Alternatively we could also use a generic author like:

    "name": "Eclipse GLSP",  
    "email": "<someGenericMailAddress>",   
    "url": "https://www.eclipse.org/glsp/"
or

    "name": "EclipseSource",  
    "email": "<mailOfPackageCreator>",   
    "url": "https://eclipsesource.com/"
The same also has to be considered for the <developers> section in pom.xml files.

If we follow the Theia/Sprotty pattern of not maintaining contributor lists in the copyright header we then have the following possibilities to mention external contributors/sponsors

The commit message
The changelog
The corresponding section in the package.json or pom.xml
 
@planger planger
Ah ok I see, thanks! Let's discuss this in a separate issue then and not block this change.
Thanks!

**Comment by planger** [comment]
We should use "Eclipse GLSP Project" as the generic stand-in for all committers and contributors in all poms and package.jsons to avoid having to manually maintain it.
E-mail address: GLSP dev mailing list
Web-site the project page: https://projects.eclipse.org/projects/ecd.glsp
