### ISSUE TITLE
Add tag "generator-v0.1.25" for generator-theia-extension v0.1.25 to fetch example files

### ISSUE THREAD

**Issue by max-elia** [eclipse-glsp/glsp#254]
Since we plan to include a glsp-example in the next release of the theia-generator, a tag is needed to fetch from.
https://github.com/eclipse-theia/generator-theia-extension

**Comment by max-elia** [comment]
Tag should be added here, since it contains the example files.
https://github.com/eclipse-glsp/glsp-examples

**Comment by tortmayr** [comment]
The tag has been added:
https://github.com/eclipse-glsp/glsp-examples/tree/generator-v0.1.25
