### ISSUE TITLE
Adjustable level of details

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#255]
For our ECE21 talk we need an example with adjustable level of detail (e.g. depending on the zoom level certain properties of a node are visible or not.

**Comment by tortmayr** [comment]
@planger I thinks we can close this one right?

**Comment by planger** [comment]
Yes, I agree... it is not something that's already clearly on the roadmap. So we can close it for now and create a new ticket, once it is planned in for the roadmap.
