### ISSUE TITLE
Mismatch Protocol and implementation for SelectAction

### ISSUE THREAD

**Issue by lforst** [eclipse-glsp/glsp#261]
In the GLSP protocol, the members of the [SelectAction](https://github.com/eclipse-glsp/glsp/blob/master/PROTOCOL.md#2931-selectaction) are defined as `selectedElementIds` and `deselectedElementIds`. The current sprotty implementation (I believe at [this](https://github.com/tortmayr/glsp-sprotty-client/blob/fa404e9c1cd4af224a983b3ee72c0e2b98b138da/src/features/select/action-definitions.ts#L38) location) has those members implemented as `selectedElementIDs` and `deselectedElementIDs` (uppercase "ID").

**Comment by planger** [comment]
Thanks for raising the issue. In fact the documentation is wrong. The code is correct.

See [server](https://github.com/eclipse-glsp/glsp-https://github.com/eclipse-glsp/glsp-server/blob/4a1d17fc858f705cd45fa768daa740acb58ba6d4/plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/SelectAction.java#L24-L25
) and [Sprotty client](https://github.com/eclipse/sprotty/blob/69a773d1a76e253195102464d3ebfd932abbf4d3/src/features/select/select.ts#L49-L50).
