### ISSUE TITLE
Example/documentation on how to handle ports (i.e., connection points of the edges/nodes) in a graph diagram

### ISSUE THREAD

**Issue by arminmoin** [eclipse-glsp/glsp#264]
Hello, could you please elaborate on the best way to implement ports for the nodes of a graph diagram? I have already implemented the frontend part (using SPort in Sprotty). However, my backend part concerning the Eclipse GLSP server is not yet working properly. For instance, I managed to have each node with one default "dummy" port upon creation of the node. But, it is not yet possible to connect the edges to the ports and/or have ports created automatically upon edge creation, etc. Is there any example for ports or can you please provide some guidance or documentation on that? Thank you very much in advance.

**Comment by planger** [comment]
Answered here: https://spectrum.chat/glsp/general/how-to-handle-ports-i-e-connection-points-of-edges-nodes-in-a-graph-diagram~92fc7305-65c4-427b-98b6-89abd23f946f
