### ISSUE TITLE
Improve creation of new elements via command palette

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#29]
The command palette should also support sort-of dynamic commands for creating new elements.
In particular, we are interested in creating new elements by specifying name and type.
(e.g. typing MyName:AutomatedTask should create a new AutomatedTask with the name label "MyName")

[migrated from https://github.com/eclipsesource/graphical-lsp/issues/265 ]

**Comment by planger** [comment]
Yeah, I think we don't need generic support for this for now. It can (and has been) done in customizations. Whenever there is a need to have generic support, we can do it. But until then, I'd close it.
