### ISSUE TITLE
Properties view for diagram editor

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#30]
We should make use of the SelectionService hook introduced in 1674493 which enables listening to model changes.

For now it's probably best to create a simple json-forms based property view with edit capabilities

see also https://github.com/eclipsesource/graphical-lsp/issues/26

**Comment by planger** [comment]
I think we can close this issue. Generic property view has been proposed to https://github.com/eclipse-theia/theia/pull/8655 and JSONForms- and model-server-based will live in EMF.Cloud. So there is no need for this ticket here in GLSP anymore.
