### ISSUE TITLE
Add end-to-end tests

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#32]
We should start adding end-to-end tests (UI) that verify the correct behavior of using the example diagram from a users-point of view.

**Comment by planger** [comment]
assign to @eneufeld

**Comment by planger** [comment]
https://github.com/eclipse-glsp/glsp-examples/pull/44

**Comment by tortmayr** [comment]
Closing for now. We can reponen this once the GLSP playwright testing components are available (https://github.com/eclipse-glsp/glsp-playwright)
