### ISSUE TITLE
[Minimal example] Pinned to version 1.14.0

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-glsp/glsp#387]
from: https://github.com/eclipse-theia/generator-theia-extension/pull/111#issuecomment-918138028

Theia is currently pinned to 1.14.0
Because of the pin, the extension still targets es5 and not es2017
We might consider an update or even remove the upper bound?

**Comment by tortmayr** [comment]
With the 0.9.0 release the previous bound to 1.4.0 is no longer necessary. Once the minimal example is updated to 0.9.0 the upper bound version restriction is no longer required
