### ISSUE TITLE
minimal-example: typo `minmal-languages.ts` > `minimal-languages.ts` 

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-glsp/glsp#390]
**Description**

There is a typo in [`glsp-examples`](https://github.com/eclipse-glsp/glsp-examples) for the following filename:

- https://github.com/eclipse-glsp/glsp-examples/blob/master/minimal/client/minimal-theia/src/common/minmal-language.ts

The filename should be updated to `minimal-languages.ts`.

**Comment by planger** [comment]
Right, thanks for catching that! We'll fix the type once we update the example for the next release planned in the next few weeks (`0.9.0`).
