### ISSUE TITLE
Resize node with enabled GridSnapper results in out of synch mouse pointer

### ISSUE THREAD

**Issue by ivy-lli** [eclipse-glsp/glsp#400]
Hi all,
I just recognized that if you try to resize a node and you have the GridSnapper enabled the behavior is really strange because the mouse pointer will get out of sync with the resize handle.

With GridSnapper:
![resize-bug-with-gridsnapper](https://user-images.githubusercontent.com/42733123/134679986-1c191ed8-e599-4445-9f94-b6104003c787.gif)

Without GridSnapper:
![resize-bug-without-gridsnapper](https://user-images.githubusercontent.com/42733123/134680148-5ef4b41c-feb3-45c9-9c6a-7dff6be9aa0c.gif)

Sadly you the move cursor is not really visible here in the gif files but you can see the final cursor positions.

Reproduce:
- Enable the `resizeFeature` on the workflow-glsp examples `TaskNode`:
  - Open the glsp-client/examples/workflow-glsp/src/di.config.ts and remove the `modelHintModule`
  - Open the glsp-client/examples/workflow-glsp/src/model.ts and add the `resizeFeature` to the `TaskNode` `DEFAULT_FEATURES` 
- Start the glsp-workflow standalone demo

To disable the GridSnapper, I just removed the binding of it inside the di.config.ts file.

Tested in Chrome and Firefox.

Kind regards

Lukas

**Comment by ivy-lli** [comment]
I think it has something to do with the `DragAwareMouseListener`. Because in the `ChangeBoundsListener#mouseMove` method is always the element which is currently hovered as target. This would result in wrong calculations of the `GridSnapper` if this one uses e.g the element.bounds to check the snapping. You can also see this if you move your cursor very slowly while resizing the element. If you do so the behaviour seems to be correct.

But this is only a guess 🙂

**Comment by planger** [comment]
It may be helpful for debugging to disable the CSS rule that hides the mouse pointer. I think I remember that @martin-fleck-at already mentioned an issue in this matter, which was the reason why the mouse pointer is set to `none` in the first place, but I don't know the details anymore.

**Comment by martin-fleck-at** [comment]
@ivy-lli Hi, you are absolutely right in that this is a bit of an usual behavior. For reasons that Philip mentioned already we initially chose another approach and decided to hide the mouse pointer to avoid confusion. However, the more common solution seems to be to properly consider the snapped position and ensure that the mouse pointer and the resize handle are in sync. I opened a PR to fix that with https://github.com/eclipse-glsp/glsp-client/pull/144:

![resize-snap](https://user-images.githubusercontent.com/19170971/136538998-1010dd1b-282d-4936-99f1-e2b7b462f21f.gif)

The nice thing is that now we can also show proper cursor feedback for moving and resizing.

**Comment by martin-fleck-at** [comment]
@ivy-lli I'm closing this task for now since the PR has been merged. If you have any follow-up issues please let us know. Thank you!

**Comment by ivy-lli** [comment]
Hi @martin-fleck-at,
Thanks for your fix, looks great! 🙂
