### ISSUE TITLE
Carefully use Arrays.asList() and Collections.emptyList() methods

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#41]
We have to be careful with the usage of `Arrays.asList()` and the util methods for empty collections (e.g. `Collections.emptyList()`). This methods return immutable (or fixed-size) collections and should not be used in classes that could potentially be subclassed/customized. As an example:
Extending a default `ActionHandler`, overwriting the `executeAction` method and simply adding a new action to the result of the super call will throw an `UnsupportedOperationException`.

As a common guideline I'd propose that we generally use `Lists.newArrayList()` (provided by guava) instead of `Arrays.asList()` and create new empty collection objects instead of using `Collections.emptyList()`

`Arrays.asList()/Collections.emptyList()` should only be used in special cases where we explicitly want to define unmutable collections.

The existing codebase should be updated accordingly.

**Comment by planger** [comment]
We can't assure that all handlers will always return mutable or immutable lists. So lets only change the default providers so that they return mutable lists. Everything else will be hard to ensure, so we will have to expect immutable classes there anyway.
