### ISSUE TITLE
Consider unit testing Selection Service

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#44]
https://github.com/eclipse-glsp/glsp-client/blob/ed5d776ccb12ae3eb48b4641941ae93c0a6a06fa/src/features/select/selection-service.ts#L51

**Comment by tortmayr** [comment]
The selection service was initially contributed by @martin-fleck-at . So this task should probably be assigned to him :wink: 
see also:
https://github.com/eclipsesource/graphical-lsp/pull/228
