### ISSUE TITLE
Improve Marquee Tool (Performance & Full element marquee behavior)

### ISSUE THREAD

**Issue by ivy-lli** [eclipse-glsp/glsp#450]
We would like to change the Marquee-Tool so it selects only elements and edges which are fully inside the mark rectangle.

While analyse the code I've detected, that the evaluation of which element is in the marquee rectangle is not very performing.
Especially if you use an older PC or turn on the CPU throttling in e.g the Chrome DevTools you notice that the UI starts to lag.

So I did some performance measures in the MarqueeMouseListener class:

Start the measure in the mouseDown method:

```java
mouseDown(target: SModelElement, event: MouseEvent): Action[] {
  this.performance = [];
  ...
}
```

Measure the evaluation and calculation of the selected elements:

```java
mouseMove(target: SModelElement, event: MouseEvent): Action[] {
  ...
  if (this.isActive) {
    const t0 = performance.now();
    ...
    const t1 = performance.now();
    this.performance.push(t1 - t0);
    return [...]
  }
}
```

Print average time:

```java
mouseUp(target: SModelElement, event: MouseEvent): Action[] {
  const avgTime = this.performance.reduce((t0, t1) => t0 + t1) / this.performance.length;
  console.log(`Eval marked elements took avg. ${avgTime} ms`);
  ...
}
```

The results where:

* avg. 0.4742640077728152 ms
* avg. 1.7843594011322235 ms with 6x CPU slowdown

I know that those numbers don't say much, but there are some code parts which should be improved, especially the evaluation of all elements on each mouseMove event.

So in the summary:
*New feature:* Marquee entire element for selection
*Improve performance*: Cache elements at enable of the Marquee-Tool

PR will follow.

**Comment by planger** [comment]
Thanks a lot, I'm looking forward to the PR!
Regarding the selection behavior, I don't have a hard opinion. I think back then we aimed at aligning it to how it works in Google Slides. There they already select if the rectangle is overlapping. I guess both options are fine... if easily possible it could be a matter of configuration, e.g. binding one of two available implementations, while hopefully both would share the performance improvement.
