### ISSUE TITLE
Missed API during state inject refactoring

### ISSUE THREAD

**Issue by eneufeld** [eclipse-glsp/glsp#458]
In https://github.com/eclipse-glsp/glsp-server/blob/388cfe6a2d861ba7935b5883790dfefd2566b0f2/plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/GModelFactory.java#L58 the state is still passed in, this was probably missed during the refactoring which allowed to inject the state

**Comment by tortmayr** [comment]
Same is true for the `NavigationTargetResolver`
