### ISSUE TITLE
Index does not update after ReconnectEdgeOperation

### ISSUE THREAD

**Issue by MoHcmp** [eclipse-glsp/glsp#460]
How to reproduce:
- create scheme with 3 items (item1, item2, item3)
- connect item1 to item2
- save scheme
- reopen scheme (close and open editor)
- change edge target from item2 to item3
- delete item3

edge will not be deleted and scheme will freeze. I investigated this problem. It's because index does not updates on reconnect operation. And still thinks that edge goes ftom item1 to item2.

**Comment by martin-fleck-at** [comment]
@MoHcmp Thank you for reporting this! I can reproduce the issue you are describing and we are working on a fix.
