### ISSUE TITLE
Cannot open editor

### ISSUE THREAD

**Issue by MoHcmp** [eclipse-glsp/glsp#465]
Can be reproduced on theia:

- open theia
- wait for glsp server initialization
- open glsp editor
- reload page
- close editor (before glsp server initialized)
- wait for glsp server initialization
- open editor

Editor will not be opened. Glsp server throws "Could not create session for client id 'id'. Another session with the same id already exists" message.
Expectaion: editor will be opened successfully.

**Comment by planger** [comment]
Thanks for sending the bug report! Can you please try to reproduce it with the 0.9.0 release?
I think this might be already fixed there as we try to recover the session from an existing id and not throw an exception anymore.

**Comment by planger** [comment]
We can't reproduce this issue on the latest master or 0.9.0. Please feel free to reopen if you can reproduce it on recent versions. Thanks!
