### ISSUE TITLE
Missing metadata of glsp-server 0.9.0 release

### ISSUE THREAD

**Issue by debovema** [eclipse-glsp/glsp#473]
Are the metadata of https://download.eclipse.org/glsp/server/p2/releases/0.9.0/ correct ?

Here's a gist of artifacts.xml / content.xml in 0.9.0 release and latest 0.9.0 nightly : https://gist.github.com/debovema/f01513eef5b1f7f9817c0d8a1c19d23b

There are missing units & artifacts in the release version compared to the latest nightly.

**Comment by tortmayr** [comment]
You are right something went wrong when publishing the p2 release repository and some source artifacts and re-exported packages were missing.
We have fixed the issue and published the updated p2 repository.
