### ISSUE TITLE
Change download scripts for server to consume npm package instead

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#483]
Currently we provide npm download scripts for obtaining a server in the client-integration packages (e.g. Theia, etc.). However, those scripts just download the latest maven snapshot. Thus, we can't control which server version they are downloading. Consequently we sometimes run into incompatible combinations.

To address this issue, we would like to publish server jars as npm packages and consume them via NPM directly instead. This way, we can get rid of the download script and can control via the package.json which version exactly to consume.

**Comment by tortmayr** [comment]
@planger Maybe we should consider to use the node-variant of the workflow example for the embedded usecases in the dev-example? This is already available via npm and could be consumed without any overhead.
