### ISSUE TITLE
Wrong type in multi-binding for context edit validators

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#508]
https://github.com/eclipse-glsp/glsp-server-node/blob/d6c44bc0711572f8312555ef663d0fbfda0d12ac/packages/server-node/src/di/diagram-module.ts#L208

```typescript
    protected configureContextEditValidators(binding: ClassMultiBinding<ContextActionsProvider>): void {
        // empty as default
    }
```

I guess correct is `ContextEditValidator`.

**Comment by sgraband** [comment]
You are right :slightly_smiling_face:. I opened PR https://github.com/eclipse-glsp/glsp-server-node/pull/9 for this. Can be closed, once that is merged.

**Comment by planger** [comment]
Merged, thanks!
