### ISSUE TITLE
Isolate the glsp-workflow example into a separate repo?

### ISSUE THREAD

**Issue by rsoika** [eclipse-glsp/glsp#522]
Hi,
it took me some hours to understand the basics of the glsp-workflow example. The confusion comes as the example code is tightly bundled with the glsp core components. So it was very hard for me to understand what is the example code and what are the glsp code.

So I isolated the example code into my own repo on github: https://github.com/rsoika/glsp-workflow-example

My question: why do we not separate the example code on eclipse-glsp into a separate repo like in my example? I think this can help new developers to better understand the concept of sever/client code as it is now in one project and no longer mixed with the glsp core code.

In case the glsp workflow example is also some test code for you own development (which I assume is the reason to bundle it with the main code), than it would make sense to rename the /examples/ folder in something like /testing/

What do you think about this?

**Comment by planger** [comment]
Yes, I totally agree. We actually do provide standalone examples here: https://github.com/eclipse-glsp/glsp-examples
However this is still work on progress. It will contain the workflow example and the minimal example with a couple of different technology combinations (VSCode, Theia, EMF or no EMF, etc.).

Those are the ongoing issues to track progress: https://github.com/eclipse-glsp/glsp/issues/479, https://github.com/eclipse-glsp/glsp/issues/449, https://github.com/eclipse-emfcloud/modelserver-glsp-integration/issues/25

So I'll mark this as a duplicate. But thanks for the great suggestion! We'll hope to be able to provide those examples in the next few weeks.
