### ISSUE TITLE
Theia depdency version range is to wide

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#535]
Currently we use "^1.0.0" as dependency range for all Theia dependencies (even in releases). This results in a couple of problems.
First and foremost we cannot guarantee that yarn resolves a compatible Theia version when the theia integration package is consumed.
"^1.0.0." while always resolve to the newest available 1.x version.
At the point of the 0.9.0 release this was Theia 1.20.0 which is perfectly fine. However, in the meantime Theia is at version 1.22.0 this version is no longer compatible but still will get resolved. There is no way for downstream projects to control the actual version (apart from using yarn resolutions).
In addition, the minimal version of 1.0.0 is also no longer compatible. At the very least the minimal version should be raised to 1.18 (ES 2017 migration). 

In general we might consider switching to peer dependencies for Theia and let the downstream project decide which actual version it wants to use (as long as its within the peer dependency version range9

**Comment by planger** [comment]
:+1:  for switching to peer dependency
