### ISSUE TITLE
Improve API documentation

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#545]
This is an umbrella issue to collect all issues that were raised in regards to the GLSP API documentation (or rather the lack of).

- [ ] API documentation for Diagram configuration is incomplete. In particular the `createDefaultXYZHint()`methods are not documented. See also https://github.com/eclipse-glsp/glsp/discussions/541#discussioncomment-2183942

- [ ] Documentation for the GLayoutOptions. Currently there is no documentation available on how to use the `GLayoutOptions` (which options are available, whats the effect) see also https://github.com/eclipse-glsp/glsp/discussions/544

- [ ] Improve JavaDoc
- [ ] Document GLSP Selection Service (client)

**Comment by rsoika** [comment]
I also think that one of the most important improvements is documenting the interfaces with javaDoc. This would help so much.

For Example the `ModelState`, `GModelState` and `RequestModelAction` show no comments even if they are so important. This makes it nearly impossible to implement a ModelSourceLoader. In the moment I feel only lost and total frustrated.

Please write on or two sentences in javadoc for each interface. This will help to better understand why interfaces exists and what they are good for. 
And of course it will avoid stupid questions asked by me in the discussion forum ;-)

**Comment by planger** [comment]
I've added Java Doc to several classes, see https://github.com/eclipse-glsp/glsp-server/pull/165

**Comment by planger** [comment]
I think this is done, from now on whenever we detect something missing, we'll try to add it.
