### ISSUE TITLE
Enable default tools on focus lost?

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#547]
Sometimes, especially while in the middle of creating an edge, it is a bit weird when you switch editor and return to the diagram editor that the tool is still active and keeps its state (e.g. you are in the middle of the edge creation).
Arguable that's a feature ;-) but also it is a bit unexpected.

Alternatively, we could enable the default tools when the editor looses focus. WDYT?

```typescript
configureActionHandler({ bind, isBound }, FocusStateChangedAction.KIND, EnableDefaultToolsOnFocusLost);
...
@injectable()
export class EnableDefaultToolsOnFocusLost implements IActionHandler {
    handle(action: Action): void | Action | ICommand {
        if (isFocusStateChangedAction(action) && !action.hasFocus) {
            return new EnableDefaultToolsAction();
        }
    }
}
```

**Comment by tortmayr** [comment]
In general I like the suggestion but I would definitively make this configurable. There might be some usecases where we want to keep the tool active if when the focus is changed. For instance, in one project we have integrated the tool palette as a separate Theia view. In this case deactivating the tool would break the functionality as the focus changes between diagram editor and external palette during tool execution.
