### ISSUE TITLE
Update to Theia 1.23.0

### ISSUE THREAD

**Issue by ndoschek** [eclipse-glsp/glsp#568]
With Theia 1.22.0 a breaking change breaks will affect our [`AbstractGLSPDiagramContextKeyService`](https://github.com/eclipse-glsp/glsp-theia-integration/blob/3655cc2dcb7836fcb191e96784bcea645b56664e/packages/theia-integration/src/browser/diagram/glsp-diagram-context-key-service.ts)
- The `activeWidget` member of the `ApplicationShell` is now probably resolved later (see [Theia's Changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md#v1220---1272022) and the corresponding [commit](https://github.com/eclipse-theia/theia/commit/2352920342db3322907f392c3d480b6d11fbe44c)).
- We need to check this properly in [`getDiagramWidget()`](https://github.com/eclipse-glsp/glsp-theia-integration/blob/master/packages/theia-integration/src/browser/diagram/glsp-diagram-context-key-service.ts#L104)

**Comment by tortmayr** [comment]
This has already been fixed with https://github.com/eclipse-glsp/glsp-theia-integration/pull/105/files
