### ISSUE TITLE
Adding/Deleting tasks via context menu does not work if multiple Diagrams are open

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#57]
The commands are sometimes executed in the wrong diagram widget.

![Peek 2020-04-01 15-06](https://user-images.githubusercontent.com/2311075/78140553-7e061e00-742a-11ea-989e-848d89137f7b.gif)

see also: https://spectrum.chat/glsp/general/trying-to-add-new-menuitemprovider~03147a72-b129-40f8-9fbc-46c63105720e

**Comment by planger** [comment]
Ha, good catch! This is a funny looking bug!
I looked into the code and found the reason. The `TheiaContextMenuService` is bound in the Theia frontend module as a singleton. That is, it will only be instantiated once in the Theia session.
Each GLSP widget will then connect once it is opened its action dispatcher to this `TheiaContextMenuService`. So the last one always wins.
We need to *create* one `TheiaContextMenuService` instance for each GLSP widget to which the GLSP widget is then connected.
