### ISSUE TITLE
Cannot build glsp-node-server

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#581]
After a fresh clone, I get the following when running `yarn`.

```
yarn run v1.22.17
$ lerna run build
lerna notice cli v4.0.0
lerna info Executing command in 4 packages: "yarn run build"
@eclipse-glsp/graph: $ yarn run clean && tsc
@eclipse-glsp/graph: $ rimraf lib
@eclipse-glsp/graph: ../../node_modules/@eclipse-glsp/ts-config/tsconfig.json(9,5): error TS5023: Unknown compiler option 'noImplicitOverride'.
@eclipse-glsp/graph: error Command failed with exit code 2.
@eclipse-glsp/graph: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 2 in '@eclipse-glsp/graph'
error Command failed with exit code 2.
```

I think this is because the `@eclipse-glsp/ts-config` is already upgraded to a higher TypeScript version, while glsp-server-node isn't.

**Comment by tortmayr** [comment]
It seems like the yarn.lock has not been committed. As a consequence the versions are not locked and a clean build will always fetch the newest version (in range).

**Comment by tortmayr** [comment]
I have removed the yarn.lock file from the `.gitignore` and commited my local yarn lock which builds just fine.
