### ISSUE TITLE
Create eclipse-integration server 0.10.0 nightly release

### ISSUE THREAD

**Issue by ivy-lli** [eclipse-glsp/glsp#586]
Up to now there is no eclipse-integration server 0.10.0 nightly release, although there are already several improvements.

https://download.eclipse.org/glsp/ide/p2/nightly/

**Comment by tortmayr** [comment]
Should be fixed with https://github.com/eclipse-glsp/glsp-eclipse-integration/pull/49

**Comment by tortmayr** [comment]
The PR has been merged and nightly builds are now successfully deployed to:
https://download.eclipse.org/glsp/ide/p2/nightly/0.10/

**Comment by ivy-lli** [comment]
Short question:
As you merged your branch, there was indeed a new nightly p2 release. But it seems that there was no new client release:
PR merged 14 days ago: https://github.com/eclipse-glsp/glsp-eclipse-integration/pull/49
Last Npm version is 21 days ago: https://www.npmjs.com/package/@eclipse-glsp/ide

**Comment by tortmayr** [comment]
Hi @ivy-lli,
there seemed to be an issue with the Eclipse Build infrastructure.  I re-triggered the nightly build and a new next version of the client should be available via npm. Thanks for catching that :+1:
