### ISSUE TITLE
Add additional glsp-examples

### ISSUE THREAD

**Issue by ndoschek** [eclipse-glsp/glsp#622]
- [x] Add glsp-example using Java server/EMF resources/Theia integration https://github.com/eclipse-glsp/glsp-examples/pull/109
- [x] Add glsp example using Node server/custom Json format/VSCode application https://github.com/eclipse-glsp/glsp-examples/pull/110
- [x] Add glsp example using Node server/custom Json format/Theia application https://github.com/eclipse-glsp/glsp-examples/pull/117
- [ ] Add links and description for example using ModelServer/Java server/EMF resources/Theia application

**Comment by planger** [comment]
We'll close it here, as the last remaining example is tracked in EMF.cloud

**Comment by ndoschek** [comment]
Just FYI, the modelserver project template was added to the website now as well (please see PR descrption for details)
