### ISSUE TITLE
Context menu does not open on MacOS

### ISSUE THREAD

**Issue by cdamus** [eclipse-glsp/glsp#628]
In my diagram editor, I want to provide a context menu on node shapes. However, on my MacOS system I cannot summon that context menu.

The problem is that the [`SelectionServiceAwareContextMenuMouseListener`][cf] is looking specifically for a hardware right button, but my mouse is a 1-button mouse in the long-standing mac tradition and on MacOS the context menu gesture is `Ctrl+Click`.

Is there some API available by which this listener can delegate to the OS to determine in a more abstract fashion whether the mouse event is the trigger for the context menu? For example, VS Code, which also is a Javascript app, supports the Mac native gesture just fine.

[cf]: /eclipse-glsp/glsp-client/blob/b3a810f8c3d8f0fe28982c74079c432e54624b35/packages/client/src/features/context-menu/selection-service-aware-context-menu-mouse-listener.ts#L40

**Comment by planger** [comment]
I guess the best would be to test for the `contextmenu` event, however Sprotty doesn't forward this event in [its mousetool](https://github.dev/eclipse/sprotty/blob/df4577570c5d95356a4ceb3ecc06754e6a099eec/packages/sprotty/src/base/views/mouse-tool.ts#L136). So either we change that in Sprotty or we test for multiple conditions (the one we test now OR `Ctrl+Click`).

**Comment by planger** [comment]
I've opened a [PR in Sprotty](https://github.com/eclipse/sprotty/pull/295) that forwards the `contextmenu` event.
