### ISSUE TITLE
Fix Export Diagram as SVG in theia-integration

### ISSUE THREAD

**Issue by ndoschek** [eclipse-glsp/glsp#642]
The export diagram SVG action (via Menu `Diagram`>`Export`) should export the current diagram as `svg` and open a file dialog to save this `svg`. This does not work anymore, the file dialog is not opened to save the file.
This was observer with the current workflow-example using theia-integration and it is also already broken for the minimal example, which uses GLSP versions `0.9.0`.

**Comment by tortmayr** [comment]
@planger  This sounds like a regression bug that we should fix for the 1.0.0 release. Do you aggree?

**Comment by planger** [comment]
Yeah would for sure be good to have that fixed with the release. However, I wouldn't consider it a blocker.
@ndoschek Do you have this task in the backlog of some project?

**Comment by ndoschek** [comment]
Yes, it is also in the backlog for ST, but I do not know when it will be planned exactly.
