### ISSUE TITLE
How to implement a NodeOperation Handler for multiple elementIDs?

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#646]
### Discussed in https://github.com/eclipse-glsp/glsp/discussions/644

<div type='discussions-op-text'>

<sup>Originally posted by **rsoika** May  7, 2022</sup>
I wonder if it is possible to implement a CreateNodeOperation Handler for multiple elementIDs? 

I can see that the AbstractCreateOperationHandler provide such a constructor

```java 
public abstract class AbstractCreateOperationHandler<T extends CreateOperation> extends AbstractOperationHandler<T>
   implements CreateOperationHandler {
   protected List<String> handledElementTypeIds;

   public AbstractCreateOperationHandler(final String... elementTypeIds) {
      this(Lists.newArrayList(elementTypeIds));
   }
....
```

But the `CreateNodeOperationHandler` which is extending the `AbstractCreateOperationHandler` does not. 

As a result I implement now a CreateXXXOperationHandler (extending the `CreateNodeOperationHandler`) for each elementID in my diagram, even if the implementation is identically. </div>

**Comment by planger** [comment]
I guess, we could also make [the constructor](https://github.com/eclipse-glsp/glsp-server/blob/39ee6c9aa37f71d989ca0efcfc49ae2f25690b3e/plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/gmodel/CreateNodeOperationHandler.java#L46) of  `CreateNodeOperationHandler` take a var arg and pass it to super, to allow for `CreateNodeOperationHandler` that can handle multiple element types.

**Comment by rsoika** [comment]
I think this issue is  covered by https://github.com/eclipse-glsp/glsp-server/pull/164

**Comment by tortmayr** [comment]
@planger Can this be closed?

**Comment by planger** [comment]
Yes, it has been fixed with https://github.com/eclipse-glsp/glsp-server/pull/164
