### ISSUE TITLE
Consistently apply `SourceModelStorage` name

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#655]
With https://github.com/eclipse-glsp/glsp-server/pull/154 we introduced a conceptual change and decided to avoid the 
term `Model Source` altogether and instead introduce and
consistently use "source model" to refer to the underlying model that we
read and write.

However, at this point this name change is not consistently applied everywhere. I found the following references to the old model source term:
- Package name of ` org.eclipse.glsp.server.features.modelsourcewatcher` [Java-Server]
- `ModelSourceChangedAction` [server & client/protocol]
- `modelSourceWatcher` feature [Client]
- `TheiaModelSourceChangedHandler` [theia]

**Comment by planger** [comment]
- https://github.com/eclipse-glsp/glsp-client/pull/184
- https://github.com/eclipse-glsp/glsp-server/pull/171
- https://github.com/eclipse-glsp/glsp-theia-integration/pull/117
- https://github.com/eclipse-glsp/glsp/pull/669
