### ISSUE TITLE
No KeyListeners if using GLSPProjectionView

### ISSUE THREAD

**Issue by ivy-lli** [eclipse-glsp/glsp#689]
I currently updated to the latest glsp next version (0.10.0-next.843026.180)

After the update I wanted to try some new features like the projection bars. They look really cool, but sadly they seem also to break any key listeners.

Without GLSPProjectionView:
`configureModelElement(context, DefaultTypes.GRAPH, GLSPGraph, SGraphView);`
![glsp-delete-element](https://user-images.githubusercontent.com/42733123/175314356-c8ec85b2-92c3-4204-b753-3fe882cba760.gif)

With GLSPProjectionView:
`configureModelElement(context, DefaultTypes.GRAPH, GLSPGraph, GLSPProjectionView);`
![glsp-no-keylistener](https://user-images.githubusercontent.com/42733123/175314882-bcdf644e-7b1c-4b9c-a7a8-4656fe4ef875.gif)

The second gif is not ideal, as you don't see anything happend, but I pressed the 'delete' key multiple times.

Maybe this is a problem of sprotty?

**Comment by ivy-lli** [comment]
Something else which is a little bit weird is that the projection bars are only visible in the theia extension, because of some missing styles which are only defined in the sprotty.css and this one is per default not in the glsp-workflow example

**Comment by planger** [comment]
@ivy-lli Thanks for the bug report! Yeah, we've only really tested and integrated the new projection bars with Theia for now.

It should hopefully be only minors to also enable them in Eclipse RCP, but I'm not sure. We don't have projection bar support in Eclipse on our roadmap, right now, but we'd be very happy to help out if you would look into it.

**Comment by ivy-lli** [comment]
Yea sure, it wasn't a hugh effort to make this bars visible in the other integrations.
It was only a little bit confusing that the workflow example enables them per default (and uses [theia css variables](https://github.com/eclipse-glsp/glsp-client/blob/master/packages/client/css/glsp-sprotty.css#L224-L256) by the way) but only the theia extension displays them.

But this bug also exists in the theia integration.

**Comment by planger** [comment]
Ah ok, now I see! Thanks!

If the projection bars break keybindings also in the Theia case (and are on by default so they break them by default in Eclipse too), then this is certainly something we should fix.
Do you already have an idea what causes that?

And yeah, the Theia-specific styles should certainly be moved to the Theia CSS.

@gabrieldulca Can you please take a look at the keybindings and move the Theia-specific styles into the Theia CSS and if it is easy add them to the VS Code integration? If they don't hurt in the Eclipse integration anymore (because the keybinding bug is fixed) then we can keep it as is; otherwise we should make them optional and only add them for the Theia integration.

**Comment by ivy-lli** [comment]
My feeling is that the additional `div` causes this problem:
![image](https://user-images.githubusercontent.com/42733123/175488787-79bef6eb-748e-44e5-b77e-b91cc9b7767d.png)
I mean normally (without projection bars) the `sprotty-graph` class is on the svg element.

With projection bars the [KeyTool](https://github.com/eclipse/sprotty/blob/master/packages/sprotty/src/base/views/key-tool.ts#L63-L70) seems to register its events on this `div` instead of the `svg` element. But I don't know if this is problem, I'm not very familiar with the sprotty/snabbdom code...

**Comment by planger** [comment]
Great, thanks for the insight! That sounds like a promising lead.
I'll ask @gabrieldulca to look into it as he worked on the integration of the projections.

**Comment by gabrieldulca** [comment]
@planger Thank you for notifying me, I will look into it!

**Comment by planger** [comment]
Closed via https://github.com/eclipse-glsp/glsp-client/pull/191

**Comment by ivy-lli** [comment]
Thanks for the fix 🥳
