### ISSUE TITLE
Update to latest vscode-json-rpc version

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#713]
Currently we are using vscode-json-rpc 5.x. This version is rather old and we should update to 8.x. 
In addition, we should probably drop the hard dependency to vscode-ws-jsonrpc. The Eclipse integration (or other adopters that want to use GLSP via websocket) can still consume a compatible version of vscode-ws-jsonrpc manually

**Comment by tortmayr** [comment]
@martin-fleck-at  already prepared an update of the client for this (https://github.com/eclipse-glsp/glsp-client/pull/210). Unfortunately this is currently blocked because the latest version of `vscode-ws-jsonrpc` requires at least node 16 as minimum version. Our current minimum is 14 (analog to Theia).
We have two options here:
1. Update our minimum to 16 or
2.  Use an older version of vscode-ws-jsonrpc (any 1.x version should work).

I would rather go for option 1 since node 14 is already without active support and reaches end-of-life in 4 months anyways. (https://endoflife.date/nodejs)

@planger wdyt?

**Comment by planger** [comment]
My only consideration against dropping support for node 14 is that Theia is still supporting it. Thus, there might be Theia-based applications still running on 14, which then couldn't use GLSP.
However, given that we only update the nightly version with that change and security support for 14 ends in 4 months, I'm not objecting to raising the min req to 16 on the nightly version.
