### ISSUE TITLE
Search feature in documentation on website is broken

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#723]
The search feature doesn't seem to work anymore on https://www.eclipse.org/glsp/documentation.

**Comment by xai** [comment]
While it might sounds like okkur/syna#848, I'm not convinced that this is the actual problem.

On each search, a GET request for `/index.json` is issued which results in a `404` if the website is not run in the webserver root but in a subpath like in our case. So this might be even a completely different problem. As the feature worked previously, my next step would be bisecting hugo and/or syna which might be a bit time consuming.

**Comment by xai** [comment]
Definitely a different issue, which I reported to [syna](https://github.com/okkur/syna/issues/882) including a potential [fix](https://github.com/okkur/syna/pull/883).
