### ISSUE TITLE
Upgrade Jetty to be compatible with Eclipse 2022-09 based product

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-glsp/glsp#764]
As [raised in the discussions](https://github.com/eclipse-glsp/glsp/discussions/763) the current version of the GLSP IDE editor is no longer compatible with newer Eclipse versions due to their upgrade to Jetty 10. This can be tested by updating the target in the eclipse-integration project to 2022-09.

**Comment by N1k145** [comment]
If I have seen it correctly also glsp server needs to be updated as the used javax.websocket (used in glsp server websocket) version changed with the jetty version.

**Comment by tortmayr** [comment]
Unfortunatley the jetty version provided by the default Eclipse Updatesite does not contain the jetty websocket plugins and is therefore not suitable for our needs. We still have to consume jetty from an external update site (e.g. https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-p2).
After discussing this with the EMF.cloud team I would even opt for updating to Jetty 11. This would allow us to keep the version at least consistent between the EMF.cloud and GLSP projects. Jetty 10 and 11 are feature identical the only difference is that Jetty 10 uses the old `javax` namespace (javax.websocket, javax.servlet) wheras Jetty 11 uses the new `jakarta` namespace.
