### ISSUE TITLE
BaseGLSPClient should handle reconnect

### ISSUE THREAD

**Issue by eneufeld** [eclipse-glsp/glsp#77]
The BaseGLSPClient should handle error on the connection better by trying a reconnect similar to how the BaseLSPClient is doing it.

---

Edit 2023-07-24:

We investigated WebSocket interrupts with the different example integrations.
The websocket server implementations will now handle a reconnect gracefully and respond to a `RequestModelAction` with the latest `modelState` (see https://github.com/eclipse-glsp/glsp-server-node/pull/54 and https://github.com/eclipse-glsp/glsp-server/pull/208).

Here is an overview of the examples that can already handle websocket connection interrupts:
- [x] GLSP standalone example (https://github.com/eclipse-glsp/glsp-client/pull/269)
- [x] GLSP Eclipse integration example (https://github.com/eclipse-glsp/glsp-eclipse-integration/pull/84)
- [x] GLSP Theia integration example (Connect to a Websocket GLSP Server) (https://github.com/eclipse-glsp/glsp-theia-integration/pull/197)
   - [x] Main feature was implemented and merged, follow-up issues need to be fixed (listed here: https://github.com/eclipse-glsp/glsp-theia-integration/pull/197#pullrequestreview-1875169697)
- [x] #1275
- [x] #1276

What is left to do:
- [x] #1277

**Comment by tortmayr** [comment]
Potentially related to #96

**Comment by ndoschek** [comment]
We have troubles with interrupting connections in a client project that is deployed on a cluster. I will look into this and back contribute the fix once we could verify it works reliably.

**Comment by ndoschek** [comment]
For the Theia use cases we should wait for this generic fix in the Theia framework to properly fix the reconnect issue for GLSP:
https://github.com/eclipse-theia/theia/pull/13082

**Comment by ndoschek** [comment]
As discussed in the last project meeting, we agreed on extracting the remaining reconnect issues (for different use cases) into separate tickets.
See #1275, #1276, #1277, #1278

Closing this now :tada:
