### ISSUE TITLE
Refactor GLSP starter to make customization easier

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#778]
The `GLSPStarter` is the central component for the webview (i.e. frontend) part of the GLSP VSCode integration.

Currently its really hard to rebind any of the default bindings and change or extend the set of initial actions.
We should at least implement a `dispatchInitialActions` method in the GLSP starter that similar to how its done in the Theia integration.

**Comment by planger** [comment]
Fixed via https://github.com/eclipse-glsp/glsp-vscode-integration/pull/51
