### ISSUE TITLE
SVG Export in Eclipse integration broken

### ISSUE THREAD

**Issue by ivy-lli** [eclipse-glsp/glsp#781]
We deliver out glsp diagram with the eclipse integration. Now we detect, that there appear a Diagram menu entry in the Eclipse when an GLSPDiagramEditor is open:
https://github.com/eclipse-glsp/glsp-eclipse-integration/blob/master/server/plugins/org.eclipse.glsp.ide.editor/plugin.xml#L7-L29

Sure this is a cool thing. But maybe someone likes to remove this, because of some reason (e.g. the export does not work).
So first of all I think it would be good if this `menuContribution` is not inside the editor plugin, but in the example workflow editor:
https://github.com/eclipse-glsp/glsp-eclipse-integration/blob/master/server/example/org.eclipse.glsp.ide.workflow.editor/plugin.xml

Second, I think this SVG Export functionality is broken. because it triggers a `ExportSVGAction`:  https://github.com/eclipse-glsp/glsp-eclipse-integration/blob/master/server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/handlers/ExportDiagramHandler.java#L25
In my opinion however (if I understand this correctly) it should trigger a `RequestExportSvgAction`. As the `ExportSVGAction` should include the final export svg content and there is no such content, so it creates a file with the content 'undefined'.
If the action would be a `RequestExportSvgAction` the client would "calculate" the content of the exporting svg and send it back to the integration via the `ExportSVGAction`.
E.g. theia-integration: https://github.com/eclipse/sprotty-theia/blob/master/src/theia/diagram-commands.ts#L180

So I think there are multiple problems here:

1. The server should know the `RequestExportSvgAction` adn register it as default client action
2. The SVG Export menu contribution of the eclipse integration should be located in the workflow example plugin.xml
3. The `ExportDiagramHandler` should send a `RequestExportSvgAction` instead of a `ExportSVGAction`

Am I correct with my analysis or did I miss something? I'm of course happy if I can contribute this changes 🙂

**Comment by planger** [comment]
@ivy-lli Thanks for the fix! Does https://github.com/eclipse-glsp/glsp-eclipse-integration/pull/65 fully solve this task so that it can be closed?

**Comment by ivy-lli** [comment]
@planger I was not able to test it on with the workflow examples and your code is not on the latest nightly release

**Comment by ivy-lli** [comment]
@planger I tested the svg export with the eclipse integration and the workflow example. The `RequestExportSvgAction` will work if I have the diagram open in an external chrome browser. In the internal webkit browser (Linux OS) nothing happens, but there is also nothing happening if I try the export with the state before this fix, so this seems to be a browser problem.

The `RequestExportSvgAction` now correctly exports the svg, instead that the height and width are not correctly set on the exported svg element, but maybe the client is not up to date in the eclipse integration? Because there was another bug fix for the export in the client, which maybe would fix this, but I'm not sure...

And I can remove the Export SVG menu entry from the Eclipse menu. So I think this is also good.

As summary: IMO this is fixed now, but maybe someone of your team likes to check that too. 
What we may should do is to increase the workflow example client version: https://github.com/eclipse-glsp/glsp-eclipse-integration/blob/master/client/package.json#L9

**Comment by ivy-lli** [comment]
@planger Can you also create an RC2 release of the eclipse ide p2 or at least create a 1.1.0 nightly release? https://download.eclipse.org/glsp/ide/p2/

**Comment by ivy-lli** [comment]
Ah I assume that would be this PR: https://github.com/eclipse-glsp/glsp-eclipse-integration/pull/58

**Comment by tortmayr** [comment]
@ivy-lli Nightly deployment should happen automatically after each merge. It seems like there is is something wrong with our CI jobs and I have to look into this.

**Comment by planger** [comment]
The CI infra has been restarted now by the Eclipse Foundation and I retriggered a build on master. :crossed_fingers:

**Comment by tortmayr** [comment]
Nighly deployments are working again:

https://download.eclipse.org/glsp/ide/p2/nightly/1.1/1.1.0.202211161006/
https://www.npmjs.com/package/@eclipse-glsp/ide/v/1.1.0-next.f685ca3.93

**Comment by ivy-lli** [comment]
Thanks a lot! I will try to update to this one in preparation of the 1.1.0 release 😀

**Comment by ivy-lli** [comment]
I updated our to the nightly eclipse integration p2. All seems to work as expected. So I think you can close this issue.
One last question, do you plan to release a RC02 so the eclipse-integration is streamlined with the other releases?

**Comment by tortmayr** [comment]
@ivy-lli We have pulished RC02 of the eclispe-integration so all components should no be streamlined an ready for the simultaneous RC03 release candiate at the beginning of december

**Comment by ivy-lli** [comment]
> @ivy-lli We have pulished RC02 of the eclispe-integration so all components should no be streamlined an ready for the simultaneous RC03 release candiate at the beginning of december

Great thanks for your work. I close this issue.
