### ISSUE TITLE
Update protocol specification

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#796]
https://github.com/eclipse-glsp/glsp/blob/master/PROTOCOL.md
The protocol definition is no longer up-to-date as the code snippets still refernence the old class-based action definitions.
We should update this (maybe after https://github.com/eclipse-glsp/glsp/issues/785 is resolved).

We should also use this opportunity to integrate the protocol specification into the GLSP website documentation. This ensures that all documentation artifacts have a central entry point.

**Comment by planger** [comment]
Yes, let's move the protocl spec to the website.
