### ISSUE TITLE
Ensure that theia-integration is fully multi-editor compatible

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#804]
In theory the glsp-integration is already architectured to also support the integration of multiple GLSP editors into the same Theia application.

However, there are currently some pitfalls that adopters might encounter when trying to integrate multiple GLSP editors.

Firstly, having multiple GLSP editors means that also multiple Diagram style sheets are loaded simultaneously which might have conflicting style definitions. We should implement a strategy to avoid "leaking" of diagram specific styles into another diagram.

~~Second there seems be an issue with conflicting bindings in the `[registerDiagramManager`](https://github.com/eclipse-glsp/glsp-theia-integration/blob/2d5654cdc32a2ee0c9ee1b69cd503ba46978b967/packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts#L48) utility method. This method also binds the `DiagramManager` and `DiagramManagerProvider` service identfier. This seems to be a remainder of the original sprotty-theia implementation and causes issues in a multi-editor context (due to ambigous bindings). Ideally we can remove this bindings or at least can find a workaround to avoid this ambiguity issues.~~
Edit: This issue is resolved with 2.x.x.

**Comment by tortmayr** [comment]
Another issue: Generic features like `layoutCommands`, `makerNavigationCommands` and `copyPaste` commands might get registered multiple times. See also:
https://github.com/eclipse-glsp/glsp/discussions/933#discussioncomment-5237806

**Comment by planger** [comment]
Should probably include: https://github.com/eclipse-glsp/glsp/issues/1201
