### ISSUE TITLE
Use node GLSP server in workflow dev example to avoid having to download server

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#813]
Now that we have a dedicated [CLI dev package](https://github.com/eclipse-glsp/glsp/tree/master/dev-packages/cli) we can start and migrating dev scripts that are used in multiple repositories to this package.
The first thing that comes to mind is the the "download:exampleServer" script that is currently used in glsp-client, glsp-theia-integration and glsp-vscode-integration.

**Comment by planger** [comment]
Instead of downloading the java server, we rather use the node server and point to it via npm dependency.
Should wait for #791 to avoid loosing functionality.
