### ISSUE TITLE
GLSP Server alignments

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#818]
This is an umbrella issue to collect all server PRs that have only been applied for one flavor (Java, Node) yet and still need to be 
aligned with the counterpart.

# Java Server
 (need to be applied to Node Server)

# Node Server 
 (need to be applied to Java Server)
- [ ] https://github.com/eclipse-glsp/glsp-server-node/pull/30
- [ ] https://github.com/eclipse-glsp/glsp-server-node/pull/28

**Comment by planger** [comment]
Let's consider creating a milestone instead of this issue.

**Comment by tortmayr** [comment]
Done https://github.com/eclipse-glsp/glsp/milestone/5
