### ISSUE TITLE
Move the website repository to the eclipse-glsp organization

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#824]
Currently the website sources are still located for historical reasons at https://github.com/eclipsesource/graphical-lsp-website.
We want to move them into the eclipse-glsp organization and use Github actions to publish the website via a push to https://github.com/eclipse-glsp/glsp-website.

I suggest to name the repository for the website sources https://github.com/eclipse-glsp/glsp-website-source

I'll trigger this process soon. So please be aware. It shouldn't cause any problems as we transfer the existing repositories so that existing PRs etc will remain intact.

Ping https://github.com/eclipse-glsp/glsp/issues/796

**Comment by tortmayr** [comment]
@planger AFAIK the website migration is completed. Can we close this?

**Comment by planger** [comment]
Yes, right! For the references:
The website sources are now hosted at https://github.com/eclipse-glsp/glsp-website-source
A Github action rebuilds the website content and pushes it to https://github.com/eclipse-glsp/glsp-website in order to publish the content to https://eclipse.org/glsp.
