### ISSUE TITLE
Theia-integration is not working with Node 18

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#837]
see https://github.com/eclipse-glsp/glsp/discussions/836#discussioncomment-4484170

**Comment by tortmayr** [comment]
As it turns out this is expected, as Theia is at the moment also not compatible with node 18.
This is currently not reflected in the engines definition of Theia but there is a [PR](https://github.com/eclipse-theia/theia/pull/12169/files) open that changes that. For the time being Theia only supports Node 16

**Comment by planger** [comment]
Wait for Theia upgrading Electron to get node 18 supported.

**Comment by tortmayr** [comment]
After the electron upgrade all current LTS versions are supported.
I tested building of
- glsp-client
- glsp-theia-integration
- glsp-vscode-integration
- glsp-server-node

And all projects can be built successfully with Node 16,18 and 20
