### ISSUE TITLE
Refactor/Improve base protocol

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#850]
We have identified a couple of issues with the base protocol that should be fixed before the next release:

## Introduce an `InitializeClientSessionResult`
Currently the serverActions returned by the `intializeServer` method are used to configure the action handlers in the session specific diagram container. This means we either have to cache the result so that we can reuse if for each client session or call `initializeServer` again just to get the result. Since this is session specific information  the better architectural decision would be to return the serverActions for the given diagram type as return value of the `initializeClientSession` method. 

## Disposal of `onActionMessage` listeners
We currently have no way of disposing actionMessage handlers registered via `onActionMessage`. The call should return a function  or object (e.g. disposable) that can be invoked to unregiser

We often also only register `onMessage` handlers that are interested in one particular clientId, so maybe we should make it possible to scope the registration to a particular client id

**Comment by planger** [comment]
Also add possibility for the client to tell the server which action types it is going to handle (like it is already possible for the opposite direction).
