### ISSUE TITLE
Align prefix of graphical model types (e.g. SEdge -> GEdge)

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#865]
Currently, every graph model element type on the server is prefixed with G, while it is prefixed in Sprotty with S.
This is a bit confusing.

**Comment by tortmayr** [comment]
With 0.14.0 sprotty renamed their entire `SModel` API and added an `Impl` suffix. In their philosophy the transfer format is called `SModel` whereas the internal client model has to be suffixed with `Impl`, In GLSP we have a different philosophy: The client/server model class are called `GModel`, `GModelElement` etc. and the transfer format (i.e. serializable) is called `GModelSchema`.

This means with 0.14.0 we have a API breaking change anyways so we should use this to align the prefixes i.e. alias/subclass all SmodelElementImpls` as `GModel...`. This should ensure full compatibility with the sprotty model whilest we can consistently use GModel on the GLSP side
