### ISSUE TITLE
Webview2 needs to be installed on Windows

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#875]
With the recent update of the Eclipse Integration we no longer rely on the deprecated Chromium support and instead use the OS-specific browser defaults. On Windows this is Edge which requires Webview2 to work properly.

We should implement a mechanism to check whether Webview2 is available (or at least document it properly)

**Comment by CamilleLetavernier** [comment]
Note: by now, Webview2 should be installed by default on any up-to-date Windows system, so using the Edge browser on SWT/Windows should be sufficient in most cases, without any specific extra installation step.

**Comment by tortmayr** [comment]
Okay, so let's close this for now. For corner cases where Webview2 is not available on an adopters system we can always implement a custom solution
