### ISSUE TITLE
`EMFDiagramModule` without binding a subclass of `EMFModelState` fails

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#896]
When using the [`EMFDiagramModule`](https://github.com/eclipse-glsp/glsp-server/blob/master/plugins/org.eclipse.glsp.server.emf/src/org/eclipse/glsp/server/emf/EMFDiagramModule.java) as a base-class without without overriding [`bindGModelState()`](https://github.com/eclipse-glsp/glsp-server/blob/master/plugins/org.eclipse.glsp.server.emf/src/org/eclipse/glsp/server/emf/EMFDiagramModule.java#L53), Guice will throw a `ProvisionException` as we bind `EMFModelState` twice:
1. in `bindGModelState()`
2. in [`configureGModelState()`](https://github.com/eclipse-glsp/glsp-server/blob/master/plugins/org.eclipse.glsp.server.emf/src/org/eclipse/glsp/server/emf/EMFDiagramModule.java#L66)

We should make the binding in (2) above dependent on whether the concrete GModel class is different from `EMFModelState`.

**Comment by ndoschek** [comment]
Resolved with [#199](https://github.com/eclipse-glsp/glsp-server/pull/199)
