### ISSUE TITLE
Improve support for container change/semantic move

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#90]
We currently provide rudimentary support for reparenting/semantic move of diagram elements. The action definiton and the typehints exist but we have no generic tool/action handler to trigger this operation. In addition, the workflow example has currently no language concept that would support reparenting.

Subissues:
- [x] #225 
- [x] #224
- [x] #219
- [x] #392

**Comment by planger** [comment]
There are a few other issues that are part of this overall support for containers and editing of elements within contains:
https://github.com/eclipse-glsp/glsp/issues/225
https://github.com/eclipse-glsp/glsp/issues/224
https://github.com/eclipse-glsp/glsp/issues/219

**Comment by tortmayr** [comment]
Closing this as all subtasks are done
