### ISSUE TITLE
unknown property error in Slabelview while building

### ISSUE THREAD

**Issue by TheDemonHuB** [eclipse-glsp/glsp#914]
Hey i just upgraded theia version from 1.27.2 to 1.34.0 

have facing unknown property error in some components of SLabelView
here is the screenshot of error & implementation 

![image](https://user-images.githubusercontent.com/57061430/218084867-99dea099-5ad4-4f75-82c5-58112dfe411e.png)
![image](https://user-images.githubusercontent.com/57061430/218084880-fc18295c-c45a-4081-a79e-b2b20c3ddc19.png)

can anyone help ??

**Comment by tortmayr** [comment]
Duplicate of https://github.com/eclipse-glsp/glsp/discussions/913
