### ISSUE TITLE
Deadlock when saving by closing dirty editor (Eclipse IDE integration)

### ISSUE THREAD

**Issue by paulreuter** [eclipse-glsp/glsp#916]
GLSPEditorRegistry.partClosed is synchronized and will block access to the GLSPEditorRegistry until all pending Actions have been dispatched.
The SaveAction triggers a SetDirtyStateAction response handled by IdeSetDirtyStateActionHandler. This is blocked due to access to the GLSPEditorRegistry.

**Comment by paulreuter** [comment]
It seems to me that the synchronized keyword only serves to gate the access to the clientIdtoDiagramEditor map. 
If that is correct, the line

clientIdtoDiagramEditor.remove(editor.getClientId());

could simply be placed in its own synchronized method, with the partClosed method no longer being synchronized. I haven't observed any adverse side effects so far.

**Comment by planger** [comment]
Thank you for looking into this, sounds good!
Can you please open a PR in https://github.com/eclipse-glsp/glsp-eclipse-integration with your proposed change so that we can test it further? Thank you!
