### ISSUE TITLE
Change bounds feedback is not dispatched as a feedback action

### ISSUE THREAD

**Issue by wss29** [eclipse-glsp/glsp#941]
Hi,
   May be it is a bug after discussing with planger. the detail is at https://github.com/eclipse-glsp/glsp/discussions/937#discussioncomment-5158504

**Comment by planger** [comment]
I've locally fixed the move issue, also fixing resize is still pending. However, we should coordinate this with https://github.com/eclipse-glsp/glsp/issues/102 to avoid having to rebase once the interfaces change a lot.
