### ISSUE TITLE
ActionDispatcher should process all messages in the same thread

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipse-glsp/glsp#97]
Currently, the ActionDispatcher executes action handlers in the thread from which the dispatch() method was called. While all messages coming from the client will come from the same thread, this becomes an issue when e.g. the server has to run some background job. In this case, the background jobs are currently not able to rely on the action dispatcher: they can dispatch messages, but only from their own thread, which may cause concurrency issues.

The ActionDispatcher should be updated to accept messages from any thread, but always process them in the same thread.

This issue also depends on #96, as the ActionDispatcher will probably have to manage its own Thread; which means it will have to shut it down when the client disconnects.

**Comment by tortmayr** [comment]
#96 is resolved now.
