### ISSUE TITLE
ModelState should use interface-injection for all subclasses

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipse-glsp/glsp#974]
Currently, GModelState is bound as an Interface+Class, and injected as an Interface (which is the recommended pattern). However, specialized subclasses (such as EMFModelState) are directly injected as classes and bound only to the GModelState interface.

While this works okay-ish when applied on a single layer, this breaks when another sub type is bound to specialize EMFModelState, as EMFModelState is no longer explicitly bound anywhere, but still used for injection. The error is difficult to see, because Guice then falls back to implicit injection (EMFModelState has a no-arg constructor, so it can be implicitly instantiated). However, implicit injection then ignores the Singleton declaration defined for the subclass. This causes multiple model states to be instantiated, thus leading to inconsistencies.

To avoid these issues, we should use interface injection for all subclasses of ModelState, and bind the most specific implementation class as a singleton, so that more specialized applications can bind their own model state implementation consistently in all parts of the GLSP server.

**Comment by ndoschek** [comment]
Resolved with [#199](https://github.com/eclipse-glsp/glsp-server/pull/199)
