### ISSUE TITLE
Support `SelectAction` without having to specify all deselected elements

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#979]
At the moment it is quite inconvenient if you'd like to set the selection for a specific set of elements disregarding the current selection. For doing that you have to create a `SelectAction` with the elements to be selected and a list of elements that you want to deselect (i.e. all other elements).

It'd be more convenient if you'd have e.g. a flag in the `SelectAction` to indicate you want to deselect all others.

See also
https://github.com/eclipse-glsp/glsp-client/blob/c6c81e0ec2ad67cb63017d4c64a7cdb3cc078dcb/packages/client/src/features/select/select-mouse-listener.ts#L54

**Comment by martin-fleck-at** [comment]
- [ ] client
- [ ] server
- [ ] eclipse-integration

**Comment by tortmayr** [comment]
@martin-fleck-at 
I have updated the list of components that need to be updated/adapted for this change
